- type: gameMapPool
  id: DefaultStarlightMapPool
  maps:
  - StarlightBagel
  - StarlightCog
  - StarlightCork
  - StarlightFland
  - StarlightHotel
  - StarlightLagan
  - StarlightLeth
  - StarlightNovoLobster
  - StarlightManor
  - StarlightMing
  - StarlightOasis
  - StarlightOrwell
  - StarlightReach
  - StarlightRefinery
  - StarlightSaltern
  - StarlightSepultum
  - StarlightStarboard
  - StarlightKiloton
  - StarlightElkridge
  - StarlightPrism
  - StarlightSilica
  - StarlightCluster
  - StarlightBox
  - StarlightPlasma
  - StarlightPacked
  - StarlightSpaceMall
  - StarlightSerpentcrest
