- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 5h
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance
  # Starlight Start
  extendedAccess:
  - Paramedic
  - Surgery
  # Starlight End

- type: startingGear
  id: ChemistGear
  equipment:
    # id: ChemistryPDA #Starlight
    ears: ClothingHeadsetMedical
    # belt: ChemBag #Starlight
    # pocket1: HandLabeler #Starlight
    # eyes: ClothingEyesGlassesChemical #Starlight
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ChemistChameleonOutfit
  job: Chemist
  equipment:
    head: ClothingHeadHatBeretMedic
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLabChem
    gloves: ClothingHandsGlovesLatex
