using Content.Client._Starlight.UserInterface; // Starlight
using Content.Client.Computer;
using Content.Shared._Starlight.Shuttles.BUIStates;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface; // Starlight
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class RadarConsoleWindow : PopOutFancyWindow, // Starlight: popout support
    IComputerWindow<NavInterfaceState>
{
    protected override Control Control => RadarScreen; // Starlight: popout support
    public event Action<EntityCoordinates>? RadarClicked; // Starlight: go to location for AI

    public RadarConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        RadarScreen.OnRadarClick += OnRadarClick; // Starlight: go to location for AI
    }

    public void UpdateState(NavInterfaceState scc, DockingPortStates dockingPortStates)  // Starlight: +dockingPortStates
    {
        RadarScreen.UpdateState(scc, dockingPortStates);  // Starlight: +dockingPortStates
    }

    #region Starlight
    /// <summary>
    /// Sends a map-click request to move the Station AI's remote eye to the specified coordinates.
    /// </summary>
    /// <param name="coordinates">The map coordinates selected by the user.</param>
    private void OnRadarClick(EntityCoordinates coordinates)
    {
        RadarClicked?.Invoke(coordinates);
    }
    #endregion
}
