- type: securityIcon
  parent: MindShieldIcon
  id: TSFMindShieldIcon
  icon:
    sprite: /Textures/_Starlight/Interface/Misc/job_icons.rsi
    state: TSF_Mindshield

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconArrestonsight
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_aos
