using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Xenobiology.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class SlimeNameChangePotionWindow : FancyWindow
    {
        // Yes I am just copying from HandLabelerWindow.xaml.cs, what do you want from me, it works
        // When I learn more about how the UI works I'll make this better and probably from the ground up
        public event Action<string>? OnNewNameChanged;
        
        /// <summary>
        /// Is the user currently entering text into the control?
        /// </summary>
        private bool _focused;
        // TODO LineEdit Make this a bool on the LineEdit control

        private string _newName = string.Empty;
        private string _initialNewName = string.Empty;

        public SlimeNameChangePotionWindow()
        {
            RobustXamlLoader.Load(this);

            LabelLineEdit.OnTextChanged += e =>
            {
                _newName = e.Text;
                OnNewNameChanged?.Invoke(_newName);
                UpdateButtons();
            };

            LabelLineEdit.OnFocusEnter += _ => _focused = true;
            LabelLineEdit.OnFocusExit += _ =>
            {
                _focused = false;
                LabelLineEdit.Text = _newName;
            };
            ResetLabelButton.OnPressed += _ => LabelLineEdit.SetText(_initialNewName, true);
            ClearLabelButton.OnPressed += _ => LabelLineEdit.SetText("", true);
        }

        protected override void Opened()
        {
            base.Opened();

            // Give the editor keyboard focus, since that's the only
            // thing the user will want to be doing with this UI
            LabelLineEdit.GrabKeyboardFocus();
        }
        
        public void SetCurrentNewName(string name)
        {
            if (name == _newName)
                return;

            _newName = name;
            if (!_focused)
            {
                LabelLineEdit.Text = name;
                UpdateButtons();
            }
        }

        public void SetInitialLabelState()
        {
            LabelLineEdit.Text = _newName;
            LabelLineEdit.CursorPosition = _newName.Length;
            LabelLineEdit.SelectionStart = 0;
            _initialNewName = _newName;
            UpdateButtons();
        }

        public void UpdateButtons()
        {
            ResetLabelButton.Disabled = (LabelLineEdit.Text == _initialNewName);
            ClearLabelButton.Disabled = (LabelLineEdit.Text == "");
        }
    }
}
