- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  startingGear: PrisonerGear
  setPreference: false
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-prisoner
  access:
  - GenpopEnter

- type: job
  id: StirStir
  name: job-name-stirstir
  description: job-description-stirstir
  playTimeTracker: JobStirStir
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 7200 # 2 hrs
  startingGear: PrisonerGear
  setPreference: false
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-security
  access:
  - GenpopEnter

- type: startingGear
  id: PrisonerGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: PrisonerPDA
    ears: ClothingHeadsetAssistant
    jumpsuit: ClothingUniformJumpsuitPrisoner
    head: ClothingHeadHatBeretPrison

- type: chameleonOutfit
  id: PrisonerChameleonOutfit
  job: Prisoner
  equipment:
    shoes: ClothingShoesColorBlack
    jumpsuit: ClothingUniformJumpsuitPrisoner
    ears: ClothingHeadsetAssistant
    gloves: ClothingHandsGlovesColorBlack
    head: ClothingHeadHatBeretPrison
