using System.Linq;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Stylesheets;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.Antags.UI;

[GenerateTypedNameReferences]
public sealed partial class AntagEntry : PanelContainer
{
    [Dependency] private JobRequirementsManager _requirements = default!;
    //[Dependency] private IClientPreferencesManager _preferencesManager = default!; // Starlight
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public const string StyleClassButton = "button";

    public event Action<bool>? OnToggled;
    public event Action? OnLoadoutPressed;

    public bool IsSelected => AntagCheckbox.Pressed;

    private readonly AntagPrototype _antag;

    public AntagEntry(AntagPrototype antag, bool enabled, HumanoidCharacterProfile? profile) // Starlight
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _antag = antag;

        // Enable mouse events so tooltips work
        MouseFilter = MouseFilterMode.Pass;

        AntagNameLabel.Text = Loc.GetString(antag.Name);
        AntagDescriptionLabel.Text = Loc.GetString(antag.Objective);

        AntagCheckbox.Pressed = enabled;
        AntagCheckbox.OnToggled += OnCheckboxToggled;

        SetupRequirements(profile); // Starlight
        SetupLoadoutButton();

        LoadoutButton.StyleClasses.Add(StyleClassButton);
        LoadoutButton.StyleClasses.Add(StyleClass.ButtonOpenBoth);

        AntagInfo.OnResized += () =>
        {
            AntagDescriptionLabel.MaxWidth = AntagInfo.Width;
        };
    }

    private void SetupRequirements(HumanoidCharacterProfile? profile) // Starlight
    {
        var locked = !_requirements.IsAllowed(_antag, profile, out var reason); // Starlight

        AntagCheckbox.Visible = !locked;
        AntagCheckbox.Disabled = locked;
        LockIcon.Visible = locked;
        #region Starlight
        /*LockIcon.TooltipSupplier = reason != null
            ? _ => new RichTextLabel { Text = reason.ToString() }
            : null;*/

        if (!reason.IsEmpty)
        {
            var tooltip = new Tooltip();
            tooltip.SetMessage(reason);
            AntagCheckbox.TooltipSupplier = _ => tooltip;
            LockIcon.TooltipSupplier = _ => tooltip;
        }
        #endregion

        if (locked)
        {
            AntagCheckbox.Pressed = false;
            OnToggled?.Invoke(IsSelected);
        }
    }

    private void SetupLoadoutButton()
    {
        var loadoutId = _antag.RoleLoadout?.FirstOrDefault();

        if (loadoutId == null || !_prototypeManager.HasIndex<RoleLoadoutPrototype>(loadoutId.Value)) // Starlight
        {
            LoadoutButton.Disabled = true;
            return;
        }

        LoadoutButton.OnPressed += _ => OnLoadoutPressed?.Invoke();
    }

    private void OnCheckboxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        OnToggled?.Invoke(args.Pressed);
    }
}
