using System.Linq;
using Content.Shared._Moffstation.Roles;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.Antags.UI;

[GenerateTypedNameReferences]
public sealed partial class SpecialRolesTab : BoxContainer
{
    [Dependency] private IPrototypeManager _prototype = default!;

    /// <summary>
    /// Event fired when trait selection changes.
    /// </summary>
    public event Action<HashSet<ProtoId<AntagPrototype>>>? OnAntagsChanged;
    public event Action<ProtoId<AntagPrototype>>? OnLoadoutPressed;

    private readonly Dictionary<ProtoId<AntagCategoryPrototype>, AntagCategory> _categoryUis = new();

    private string _currentSearchText = string.Empty;

    public SpecialRolesTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBar.OnTextChanged += OnSearchTextChanged;

        PopulateCategories(null, null); // Starlight
    }

    private void PopulateCategories(IReadOnlySet<ProtoId<AntagPrototype>>? selectedAntags, HumanoidCharacterProfile? profile) // Starlight
    {
        var expandedState = _categoryUis.ToDictionary(kvp => kvp.Key, kvp => kvp.Value.IsExpanded);

        CategoriesContainer.RemoveAllChildren();
        _categoryUis.Clear();

        var categories = _prototype.EnumeratePrototypes<AntagCategoryPrototype>()
            .OrderBy(c => c.Default)
            .ThenBy(c => c.Priority)
            .ThenBy(c => c.Name)
            .ToList();

      // This is abysmal shitcode
      // However, I don't want to have to remember to add a new antag to a category every time a new one gets added, so for maintainability it stays
      var remainingAntags = _prototype.EnumeratePrototypes<AntagPrototype>()
          .Where(a => a.SetPreference)
          .ToList();

        foreach (var category in categories)
        {
            var antags = new List<AntagPrototype>();
            if (category.Default)
                antags.AddRange(remainingAntags);

            foreach (var antagId in category.Antags)
            {
                if (!_prototype.TryIndex(antagId, out var antag))
                    continue;

                remainingAntags.Remove(antag);
                antags.Add(antag);
            }

            if (antags.Count <= 0)
                continue;

            var expanded = expandedState.TryGetValue(category.ID, out var prev) ? prev : (bool?)null;
            var categoryUi = new AntagCategory(category, antags, profile, selectedAntags, expanded); // Starlight
            categoryUi.OnAntagToggled += OnAntagToggled;
            categoryUi.OnLoadoutPressed += id => OnLoadoutPressed?.Invoke(id);
            _categoryUis[category.ID] = categoryUi;
            CategoriesContainer.AddChild(categoryUi);

        }

        ApplySearchFilter();
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _currentSearchText = args.Text.Trim();
        ApplySearchFilter();
    }

    private void ApplySearchFilter()
    {
        foreach (var (_, categoryUi) in _categoryUis)
        {
            categoryUi.FilterAntags(_currentSearchText);
        }
    }

    private void OnAntagToggled(ProtoId<AntagPrototype> antagId, bool selected)
    {
        #region Starlight
        /*var allSelected = _categoryUis.Values
            .SelectMany(c => c.GetSelectedAntagIds())
            .ToHashSet();*/
        #endregion

        OnAntagsChanged?.Invoke(GetSelectedAntagIds()); // Starlight
    }

    public HashSet<ProtoId<AntagPrototype>> RefreshAntags(HumanoidCharacterProfile? profile) // Starlight
    {
        PopulateCategories(profile?.AntagPreferences, profile); // Starlight
        return GetSelectedAntagIds(); // Starlight
    }

#region Starlight
    private HashSet<ProtoId<AntagPrototype>> GetSelectedAntagIds()
    {
        return _categoryUis.Values.SelectMany(category => category.GetSelectedAntagIds()).ToHashSet();
    }

#endregion
}
