- type: antag
  id: SSF
  name: roles-antag-ssf-name
  antagonist: true
  setPreference: false
  objective: roles-antag-ssf-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # 10h
  playTimeTracker: AntagSSF
