- type: job
  id: Magistrate
  name: job-name-magistrate
  description: job-description-magistrate
  playTimeTracker: JobMagistrate
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 180000 #50 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10h
    - !type:RolesRequirement
      proto: ExtRolesReq
    - !type:TraitsRequirement
      traits:
        - Iterator
        - Muted
      inverted: true
  startingGear: MagistrateGear
  icon: "JobIconMagistrate"
  rules: job-rules-corporate-aligned
  supervisors: job-supervisors-nanotrasen
  setPreference: true
  displayWeight: 5
  access:
  - Magistrate
  - IAA
#  - Lawyer # Lawyer is now for Lawyers, not IAAs/Magis.
  - Brig
  - Security
  - Command
  - Maintenance
  - GenpopEnter
  - GenpopLeave
  - Debrief
  - NTPersonnel
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: MagistrateGear
  equipment:
    #jumpsuit: MagistrateUniformSuit
    #shoes: ClothingShoesBootsLaceup
    #eyes: ClothingEyesGlassesSecurity
    #gloves: ClothingHandsGlovesColorWhite
    #outerClothing: ClothingOuterRobesJudge
    id: MagistratePDA
    ears: ClothingHeadsetMagistrate
    #head: ClothingHeadHatPwig
    belt: BoxFolderNanoTrasenClipboard
  storage:
    back:
    - RubberStampMagistrate
    - ClothingNeckLawyerbadge
    - GavelHammer
    - GavelBlock
    - Flash
    #- MagistrateUniformSkirt

- type: chameleonOutfit
  id: MagistrateChameleonOutfit
  job: Magistrate
  equipment:
    head: ClothingHeadHatPwig
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterRobesMagistrate
    misc: ClothingNeckLawyerbadge # Starlight change slot to misc.
    gloves: ClothingHandsGlovesColorWhite
