using System.Linq;
using Content.Client._Afterlight.Silicons.Borgs.UI; // Afterlight
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared._Afterlight.Prototypes; // Afterlight
using Content.Shared._Afterlight.Silicons; // Afterlight
using Content.Shared._Afterlight.Silicons.Borgs; // Afterlight
using Content.Shared.Guidebook;
using Content.Shared.Silicons.Borgs;
using Content.Shared.Silicons.Borgs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Client.Players.PlayTimeTracking; // Starlight-edit
using Robust.Client.Player; // Starlight-edit

namespace Content.Client.Silicons.Borgs;

/// <summary>
/// Menu used by borgs to select their type.
/// </summary>
/// <seealso cref="BorgSelectTypeUserInterface"/>
/// <seealso cref="BorgSwitchableTypeComponent"/>
[GenerateTypedNameReferences]
public sealed partial class BorgSelectTypeMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entManager = default!; // Starlight-edit
    [Dependency] private readonly IPlayerManager _playerManager = default!; // Starlight-edit
    [Dependency] private readonly JobRequirementsManager _requirementsManager = default!; // Starlight-edit

    private BorgTypePrototype? _selectedBorgType;

    public event Action<ProtoId<BorgTypePrototype>>? ConfirmedBorgType;
    public event Action<EntityPrototype?>? ConfirmBorgSubtype; // Starlight event - borg subtypes

    private static readonly List<ProtoId<GuideEntryPrototype>> GuidebookEntries = new() { "Cyborgs", "Robotics" };

    public BorgSelectTypeMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Starlight: All logic moved to method

        ConfirmTypeButton.OnPressed += ConfirmButtonPressed;
        HelpGuidebookIds = GuidebookEntries;

        // Afterlight - borg subtypes
        ChassisSpriteSelection.SubtypeSelected += () => ConfirmTypeButton.Disabled = false;
        // Afterlight end
    }
    
    // Starlight-start: Move from BorgSelectTypeMenu to method
    public void SetupMenu(EntityUid owner)
    {
        // Starlight-start: Available types
        if (!_entManager.TryGetComponent<BorgSwitchableTypeComponent>(owner, out var switchableType))
            return;
        // Starlight-end

        var group = new ButtonGroup();
        // Starlight-start: Available types
        if (switchableType.AvailableTypes.Any())
            foreach (var borgTypeId in switchableType.AvailableTypes)
            {
                if (!_prototypeManager.TryIndex<BorgTypePrototype>(borgTypeId, out var borgType))
                    continue;

                var button = new Button
                {
                    Text = PrototypeName(borgType),
                    Group = group,
                };
                button.OnPressed += _ =>
                {
                    //_selectedBorgType = borgType; Starlight: Already added at UpdateInformation
                    UpdateInformation(borgType);
                };
                button.Disabled = !_requirementsManager.CheckRequirementsForNonRole(borgType.Requirements, _playerManager.LocalSession, null, out _); // Starlight-edit
                SelectionsContainer.AddChild(button);
            }
        else
            // Starlight-end
            foreach (var borgType in _prototypeManager.EnumeratePrototypes<BorgTypePrototype>().OrderBy(PrototypeName))
            {
                var button = new Button
                {
                    Text = PrototypeName(borgType),
                    Group = group,
                };
                button.OnPressed += _ =>
                {
                    //_selectedBorgType = borgType; Starlight: Already added at UpdateInformation
                    UpdateInformation(borgType);
                };
                button.Disabled = !_requirementsManager.CheckRequirementsForNonRole(borgType.Requirements, _playerManager.LocalSession, null, out _); // Starlight-edit
                SelectionsContainer.AddChild(button);
            }

    }
    // Starlight-end

    private void UpdateInformation(BorgTypePrototype prototype)
    {
        _selectedBorgType = prototype;

        InfoContents.Visible = true;
        InfoPlaceholder.Visible = false;
        // ConfirmTypeButton.Disabled = false; Starlight

        // Afterlight - borg subtype
        if (_selectedBorgType != null)
        {
            ChassisSpriteSelection.Update(_selectedBorgType);
            ConfirmTypeButton.Disabled = ChassisSpriteSelection.SubtypePrototype == null;
        }
        // Afterlight end

        NameLabel.Text = PrototypeName(prototype);
        DescriptionLabel.Text = Loc.GetString($"borg-type-{prototype.ID}-desc");
        ChassisView.SetPrototype(prototype.DummyPrototype);
    }

    private void ConfirmButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        if (_selectedBorgType == null)
            return;

        ConfirmBorgSubtype?.Invoke(ChassisSpriteSelection.SubtypePrototype); // Afterlight
        ConfirmedBorgType?.Invoke(_selectedBorgType);
    }

    private static string PrototypeName(BorgTypePrototype prototype)
    {
        return Loc.GetString($"borg-type-{prototype.ID}-name");
    }
}
