- type: job
  id: Reporter
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: JobReporter
  requirements: # Starlight BEGIN
    - !type:OverallPlaytimeRequirement
      time: 4h # Starlight END
  startingGear: ReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Journalism # Starlight start
  extendedAccess:
  - Theatre # Starlight end

- type: startingGear
  id: ReporterGear
  equipment:
    #shoes: ClothingShoesColorWhite # 🌟Starlight🌟
    id: ReporterPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff
  # Starlight Start
  storage:
    back:
    - TapeRecorder
    - CassetteTape
    - CassetteTape
    - RubberStampReporter
    - ClothingOuterPressArmor
    - Wrench
    - NetworkConfigurator
  # Starlight End

- type: chameleonOutfit
  id: ReporterChameleonOutfit
  job: Reporter
  equipment:
    head: ClothingHeadHatFedoraGrey
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterCoatTrench
    neck: ClothingNeckTieRed
    gloves: ClothingHandsGlovesFingerless
