using Content.Client.Pinpointer.UI;
using Content.Shared._Starlight.Cargo.MailCompanion;
using Content.Shared.Medical.SuitSensor;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Numerics;
using Content.Client._Starlight.UserInterface;

namespace Content.Client._Starlight.Cargo.MailCompanion;

[GenerateTypedNameReferences]
public sealed partial class MailCompanionWindow : PopOutFancyWindow
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private readonly SharedTransformSystem _transformSystem;
    private readonly SpriteSystem _spriteSystem;
    private Texture? _blipTexture;

    protected override Control Control => RootContainer;

    public MailCompanionWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _transformSystem = _entManager.System<SharedTransformSystem>();
        _spriteSystem = _entManager.System<SpriteSystem>();
        NavMap.ShowFocusedEntityPanel = false;
        NavMap.AllowManualRecentering = false;
        JobIcon.TextureScale = new Vector2(2f, 2f);
    }

    public void Set(string stationName, EntityUid? mapUid)
    {
        _blipTexture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));

        if (_entManager.TryGetComponent<TransformComponent>(mapUid, out var xform))
            NavMap.MapUid = xform.GridUid;
        else
            NavMap.Visible = false;

        StationName.AddStyleClass("LabelBig");
        StationName.Text = string.IsNullOrWhiteSpace(stationName)
            ? Loc.GetString("mail-companion-window-no-station")
            : stationName;
        NavMap.ForceNavMapUpdate();
    }

    public void UpdateState(MailCompanionState state, EntityUid owner)
    {
        ClearMap();
        UpdateMonitorBlip(owner);

        var recipient = string.IsNullOrWhiteSpace(state.RecipientName)
            ? Loc.GetString("mail-companion-recipient-none")
            : state.RecipientName;

        RecipientLabel.Text = Loc.GetString("mail-companion-window-recipient", ("recipient", recipient));
        StatusLabel.Text = Loc.GetString("mail-companion-window-status", ("status", Loc.GetString(GetStatusLocId(state.Status))));

        var time = state.TimeRemaining > TimeSpan.Zero
            ? state.TimeRemaining.ToString(@"mm\:ss")
            : "--:--";
        TimerLabel.Text = state.Status == MailCompanionStatus.Cooldown
            ? Loc.GetString("mail-companion-window-cooldown", ("time", time))
            : Loc.GetString("mail-companion-window-time", ("time", time));

        var tracked = state.TrackedSensor;
        if (tracked?.Coordinates != null)
        {
            ShowTrackedTarget(tracked);
        }
        else
        {
            JobLabel.Text = Loc.GetString("mail-companion-window-job", ("job", Loc.GetString("mail-companion-job-unknown")));
            JobIcon.Visible = false;
            CoordinatesLabel.Text = Loc.GetString("mail-companion-window-coordinates", ("coordinates", Loc.GetString("mail-companion-coordinates-unavailable")));
        }

        HintLabel.SetMessage(Loc.GetString(GetHintLocId(state.Status)));
    }

    private void ShowTrackedTarget(SuitSensorStatus tracked)
    {
        JobLabel.Text = Loc.GetString("mail-companion-window-job", ("job", tracked.Job));

        if (_prototypeManager.TryIndex<JobIconPrototype>(tracked.JobIcon, out var proto))
        {
            JobIcon.Texture = _spriteSystem.Frame0(proto.Icon);
            JobIcon.Visible = true;
        }
        else
        {
            JobIcon.Visible = false;
        }

        var coordinates = _entManager.GetCoordinates(tracked.Coordinates);
        if (coordinates != null)
        {
            var mapCoordinates = _transformSystem.ToMapCoordinates(coordinates.Value);
            CoordinatesLabel.Text = Loc.GetString("mail-companion-window-coordinates",
                ("coordinates", $"{(int) mapCoordinates.X}, {(int) mapCoordinates.Y}"));

            if (NavMap.Visible && _blipTexture != null)
            {
                NavMap.LocalizedNames[tracked.SuitSensorUid] = tracked.Name + ", " + tracked.Job;
                NavMap.TrackedEntities[tracked.SuitSensorUid] =
                    new NavMapBlip(CoordinatesToLocal(coordinates.Value), _blipTexture, Color.LimeGreen, true);
                NavMap.Focus = tracked.SuitSensorUid;
                NavMap.CenterToCoordinates(coordinates.Value);
            }
        }
        else
        {
            CoordinatesLabel.Text = Loc.GetString("mail-companion-window-coordinates", ("coordinates", Loc.GetString("mail-companion-coordinates-unavailable")));
        }
    }

    private void UpdateMonitorBlip(EntityUid owner)
    {
        if (_blipTexture == null || !_entManager.TryGetComponent<TransformComponent>(owner, out var xform))
            return;

        NavMap.TrackedEntities[_entManager.GetNetEntity(owner)] = new NavMapBlip(CoordinatesToLocal(xform.Coordinates), _blipTexture, Color.Cyan, true, false);
    }

    private void ClearMap()
    {
        NavMap.TrackedCoordinates.Clear();
        NavMap.TrackedEntities.Clear();
        NavMap.LocalizedNames.Clear();
        NavMap.Focus = null;
    }

    private EntityCoordinates CoordinatesToLocal(EntityCoordinates refCoords)
        => NavMap.MapUid != null
            ? _transformSystem.WithEntityId(refCoords, (EntityUid)NavMap.MapUid)
            : refCoords;

    private static string GetStatusLocId(MailCompanionStatus status)
        => status switch
        {
            MailCompanionStatus.Idle => "mail-companion-status-idle",
            MailCompanionStatus.Tracking => "mail-companion-status-tracking",
            MailCompanionStatus.Cooldown => "mail-companion-status-cooldown",
            MailCompanionStatus.SensorsOff => "mail-companion-status-sensors-off",
            MailCompanionStatus.TrackingUnavailable => "mail-companion-status-tracking-unavailable",
            MailCompanionStatus.RecipientUnavailable => "mail-companion-status-recipient-unavailable",
            MailCompanionStatus.DeliveryOpened => "mail-companion-status-delivery-opened",
            MailCompanionStatus.DeliveryAlreadyOpened => "mail-companion-status-delivery-already-opened",
            MailCompanionStatus.Expired => "mail-companion-status-expired",
            _ => "mail-companion-status-idle",
        };

    private static string GetHintLocId(MailCompanionStatus status)
        => status switch
        {
            MailCompanionStatus.Tracking => "mail-companion-hint-tracking",
            MailCompanionStatus.Cooldown => "mail-companion-hint-cooldown",
            MailCompanionStatus.SensorsOff => "mail-companion-hint-sensors-off",
            MailCompanionStatus.TrackingUnavailable => "mail-companion-hint-tracking-unavailable",
            MailCompanionStatus.RecipientUnavailable => "mail-companion-hint-recipient-unavailable",
            MailCompanionStatus.DeliveryOpened => "mail-companion-hint-delivery-opened",
            MailCompanionStatus.DeliveryAlreadyOpened => "mail-companion-hint-delivery-already-opened",
            MailCompanionStatus.Expired => "mail-companion-hint-expired",
            _ => "mail-companion-hint-idle",
        };
}
