using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Starlight.SecureTerminal;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Content.Client.Stylesheets;

namespace Content.Client._Starlight.SecureTerminal;

[GenerateTypedNameReferences]
public sealed partial class SecureCommandTerminalWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _protos = default!;
    [Dependency] private IGameTiming _timing = default!;

    public event Action<string>? OnRequest;
    public event Action<string>? OnAuthorize;
    public event Action<string>? OnDeny;
    public event Action<string>? OnRecall;

    private string? _selectedRequestId;
    private Button? _selectedRequestButton;
    private readonly Dictionary<string, Button> _requestButtons = new();
    private SecureCommandTerminalInterfaceState? _lastState;

    // Double-click tracking for the Request button
    private string? _pendingConfirmId;

    public SecureCommandTerminalWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        RequestButton.OnPressed += _ => OnRequestPressed();
        AuthorizeButton.OnPressed += _ =>
        {
            if (_selectedRequestId != null) OnAuthorize?.Invoke(_selectedRequestId);
        };
        DenyButton.OnPressed += _ =>
        {
            if (_selectedRequestId != null) OnDeny?.Invoke(_selectedRequestId);
        };
        RecallButton.OnPressed += _ =>
        {
            if (_selectedRequestId != null) OnRecall?.Invoke(_selectedRequestId);
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lastState == null || _selectedRequestId == null) return;

        var proposal = _lastState.Proposals.Find(p => p.RequestId == _selectedRequestId);
        if (proposal is { Status: SecureTerminalProposalStatus.Activating, ActivateAt: not null })
        {
            var remaining = proposal.ActivateAt.Value - _timing.CurTime;
            if (remaining <= TimeSpan.Zero)
                remaining = TimeSpan.Zero;
            CountdownLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("secure-terminal-countdown-label",
                ("minutes", (int)remaining.TotalMinutes),
                ("seconds", remaining.Seconds))));
            CountdownLabel.Visible = true;
        }
        else
        {
            CountdownLabel.Visible = false;
        }
    }

    public void UpdateState(SecureCommandTerminalInterfaceState state)
    {
        _lastState = state;
        if (_requestButtons.Count == 0)
            RebuildRequestList(state);
        else
            UpdateRequestButtons(state);
        RefreshRightPanel(state);
    }

    private void RebuildRequestList(SecureCommandTerminalInterfaceState state)
    {
        _selectedRequestButton = null;
        _requestButtons.Clear();
        RequestListContainer.RemoveAllChildren();

        var allProtos = _protos.EnumeratePrototypes<SecureCommandTerminalRequestPrototype>()
            .OrderBy(p => p.SortOrder).ThenBy(p => p.ID)
            .ToList();

        // Build lookup: parentId → children
        var children = allProtos
            .Where(p => p.ParentId != null)
            .GroupBy(p => p.ParentId!)
            .ToDictionary(g => g.Key, g => g.ToList());

        foreach (var proto in allProtos.Where(p => p.ParentId == null))
        {
            AddRequestButton(proto, state, indent: false);
        }
    }

    private void AddRequestButton(SecureCommandTerminalRequestPrototype proto,
        SecureCommandTerminalInterfaceState state, bool indent)
    {
        var isUsed = state.UsedOnce.Contains(proto.ID);
        var onCooldown = state.CoolingDown.ContainsKey(proto.ID);
        var wrongAlert = proto.RequiresAlertLevel != null && state.CurrentAlertLevel != proto.RequiresAlertLevel;
        var needsWar = proto.RequiresWarDeclared && !state.IsWarDeclared;
        var needsNoWar = proto.RequiresWarNotDeclared && state.IsWarDeclared;
        var alertMinutesElapsed = (_timing.CurTime - state.AlertLevelSetAt).TotalMinutes;
        var alertNotLongEnough = proto.RequiresAlertActiveMinutes > 0 && alertMinutesElapsed < proto.RequiresAlertActiveMinutes;
        var isDeployed = state.DeployedArmories.ContainsKey(proto.ID);
        var unavailable = isUsed || needsWar || needsNoWar || onCooldown || wrongAlert || alertNotLongEnough;

        var proposal = state.Proposals.Find(p => p.RequestId == proto.ID);
        var statusSuffix = GetStatusSuffix(proposal, onCooldown, isUsed, wrongAlert, needsWar, proto.RequiresAlertLevel, isDeployed);

        var prefix = indent ? "  └ " : "- ";
        var btn = new Button
        {
            Text = $"{prefix}{Loc.GetString(proto.Name)}{statusSuffix}",
            Disabled = false, // still clickable to read info
            Pressed = _selectedRequestId == proto.ID,
            Margin = indent ? new Thickness(12, 1, 0, 1) : new Thickness(0, 2),
            MinHeight = 28,
        };
        if (isDeployed)
            btn.ModulateSelfOverride = Color.FromHex("#33aa55");
        else if (unavailable)
            btn.ModulateSelfOverride = Color.FromHex("#cc3333");

        var protoId = proto.ID; // capture
        // Changed to pressed because toggle did horrible things
        btn.OnPressed += _ =>
        {
            if (_selectedRequestButton is { } previousButton)
                previousButton.Pressed = false;

            _selectedRequestId = protoId;
            _selectedRequestButton = btn;
            btn.Pressed = true;
            _pendingConfirmId = null;
            RefreshRightPanel(_lastState!);
        };

        RequestListContainer.AddChild(btn);
        _requestButtons[proto.ID] = btn;
    }

    private void UpdateRequestButtons(SecureCommandTerminalInterfaceState state)
    {
        foreach (var proto in _protos.EnumeratePrototypes<SecureCommandTerminalRequestPrototype>())
        {
            if (!_requestButtons.TryGetValue(proto.ID, out var button))
                continue;

            var isUsed = state.UsedOnce.Contains(proto.ID);
            var onCooldown = state.CoolingDown.ContainsKey(proto.ID);
            var wrongAlert = proto.RequiresAlertLevel != null && state.CurrentAlertLevel != proto.RequiresAlertLevel;
            var needsWar = proto.RequiresWarDeclared && !state.IsWarDeclared;
            var needsNoWar = proto.RequiresWarNotDeclared && state.IsWarDeclared;
            var alertMinutesElapsed = (_timing.CurTime - state.AlertLevelSetAt).TotalMinutes;
            var alertNotLongEnough = proto.RequiresAlertActiveMinutes > 0 && alertMinutesElapsed < proto.RequiresAlertActiveMinutes;
            var isDeployed = state.DeployedArmories.ContainsKey(proto.ID);
            var proposal = state.Proposals.Find(p => p.RequestId == proto.ID);

            button.Text = $"- {Loc.GetString(proto.Name)}{GetStatusSuffix(proposal, onCooldown, isUsed, wrongAlert, needsWar, proto.RequiresAlertLevel, isDeployed)}";
            button.ModulateSelfOverride = isDeployed
                ? Color.FromHex("#33aa55")
                : isUsed || needsWar || needsNoWar || onCooldown || wrongAlert || alertNotLongEnough
                    ? Color.FromHex("#cc3333")
                    : null;
        }
    }

    private string GetStatusSuffix(SecureTerminalProposalState? proposal, bool onCooldown, bool usedOnce,
        bool wrongAlert, bool needsWar, string? _, bool isDeployed = false)
    {
        if (usedOnce) return " [USED]";
        if (isDeployed) return " [Deployed]";
        if (onCooldown) return " [CD]";
        if (wrongAlert || needsWar) return "";
        if (proposal == null) return "";
        return proposal.Status switch
        {
            SecureTerminalProposalStatus.Pending => " [Pending]",
            SecureTerminalProposalStatus.Activating => " [Activating]",
            _ => "",
        };
    }

    private void RefreshRightPanel(SecureCommandTerminalInterfaceState state)
    {
        if (_selectedRequestId == null || !_protos.TryIndex<SecureCommandTerminalRequestPrototype>(_selectedRequestId, out var proto))
        {
            InfoLabel.SetMessage(Loc.GetString("secure-terminal-select-request"));
            RequestButton.Disabled = true;
            AuthorizeButton.Disabled = true;
            DenyButton.Disabled = true;
            RecallButton.Visible = false;
            RecallButton.Disabled = true;
            ChildActionsContainer.RemoveAllChildren();
            AuthDescLabel.SetMessage(string.Empty);
            AuthorizerListContainer.RemoveAllChildren();
            CountdownLabel.Visible = false;
            return;
        }

        // Info
        var warNote = proto.RequiresWarDeclared && !state.IsWarDeclared
            ? $"\n[color=red]{Loc.GetString("secure-terminal-requires-war-note")}[/color]"
            : string.Empty;
        var noWarNote = proto.RequiresWarNotDeclared && state.IsWarDeclared
            ? $"\n[color=red]{Loc.GetString("secure-terminal-requires-no-war-note")}[/color]"
            : string.Empty;
        var alertNote = proto.RequiresAlertLevel != null && state.CurrentAlertLevel != proto.RequiresAlertLevel
            ? $"\n[color=red]{Loc.GetString("secure-terminal-requires-alert-note", ("level", proto.RequiresAlertLevel.ToUpperInvariant()))}[/color]"
            : string.Empty;
        string alertTimeNote;
        if (proto.RequiresAlertActiveMinutes > 0)
        {
            var elapsed = (_timing.CurTime - state.AlertLevelSetAt).TotalMinutes;
            if (elapsed < proto.RequiresAlertActiveMinutes)
            {
                var minsLeft = (int)Math.Ceiling(proto.RequiresAlertActiveMinutes - elapsed);
                alertTimeNote = $"\n[color=orange]{Loc.GetString("secure-terminal-alert-time-remaining", ("minutes", minsLeft))}[/color]";
            }
            else
            {
                alertTimeNote = string.Empty;
            }
        }
        else
        {
            alertTimeNote = string.Empty;
        }
        string cooldownNote;
        if (state.CoolingDown.TryGetValue(proto.ID, out var cdEnd))
        {
            var remaining = (int)Math.Ceiling((cdEnd - _timing.CurTime).TotalMinutes);
            if (remaining < 1) remaining = 1;
            cooldownNote = $"\n[color=orange]{Loc.GetString("secure-terminal-on-cooldown-note", ("minutes", remaining))}[/color]";
        }
        else
        {
            cooldownNote = string.Empty;
        }
        var usedNote = string.Empty;
        if (state.UsedOnce.Contains(proto.ID))
        {

            if (proto.ActionType == SecureTerminalActionType.Armory)
                usedNote = $"\n[color=gray]{Loc.GetString("secure-terminal-used-note")}[/color]";
            else
                usedNote = $"\n[color=gray]{Loc.GetString("secure-terminal-already-used")}[/color]";
        }

        InfoLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(
            $"{Loc.GetString(proto.Description)}" +
            GetSalaryModifierNote(proto) +
            (proto.Fee > 0 ? $"\n{Loc.GetString("secure-terminal-fee-note", ("fee", proto.Fee))}" : string.Empty) +
            (proto.ActivationDelaySecs <= 0
                ? $"\n{Loc.GetString("secure-terminal-delay-note-immediate")}"
                : $"\n{Loc.GetString("secure-terminal-delay-note", ("minutes", Math.Max(1, proto.ActivationDelaySecs / 60)))}") +
            warNote + noWarNote + alertNote + alertTimeNote + cooldownNote + usedNote));

        // Request button – available if no pending/activating proposal and not on CD
        var proposal = state.Proposals.Find(p => p.RequestId == proto.ID);
        var isDeployed = state.DeployedArmories.ContainsKey(proto.ID);
        var alertMinutesElapsed = (_timing.CurTime - state.AlertLevelSetAt).TotalMinutes;
        var canRequest = proposal == null
            && !isDeployed
            && !state.CoolingDown.ContainsKey(proto.ID)
            && !state.UsedOnce.Contains(proto.ID)
            && state.Proposals.Count == 0
            && !(proto.RequiresWarDeclared && !state.IsWarDeclared)
            && !(proto.RequiresWarNotDeclared && state.IsWarDeclared)
            && !(proto.RequiresAlertLevel != null && state.CurrentAlertLevel != proto.RequiresAlertLevel)
            && !(proto.RequiresAlertActiveMinutes > 0 && alertMinutesElapsed < proto.RequiresAlertActiveMinutes);

        // Recall button — shown during activating countdown or while armory is deployed
        var isActivating =
            proto.ActionType == SecureTerminalActionType.Armory &&
            proposal?.Status == SecureTerminalProposalStatus.Activating;
        var showRecall = isActivating || isDeployed;
        RecallButton.Visible = showRecall;
        if (showRecall && proto.RecallMinDelaySecs > 0)
        {
            TimeSpan authorizedAt;
            if (isActivating && proposal!.ActivateAt.HasValue)
                authorizedAt = proposal.ActivateAt.Value - TimeSpan.FromSeconds(proto.ActivationDelaySecs);
            else if (state.DeployedArmories.TryGetValue(proto.ID, out var deployedAuthorizedAt))
                authorizedAt = deployedAuthorizedAt;
            else
                authorizedAt = TimeSpan.Zero;

            var recallAvailableAt = authorizedAt + TimeSpan.FromSeconds(proto.RecallMinDelaySecs);
            var secsLeft = (recallAvailableAt - _timing.CurTime).TotalSeconds;
            if (secsLeft > 0)
            {
                var minsLeft = (int)Math.Ceiling(secsLeft / 60.0);
                RecallButton.Disabled = true;
                RecallButton.Text = Loc.GetString("secure-terminal-recall-locked", ("minutes", minsLeft));
            }

            else
            {
                RecallButton.Disabled = false;
                RecallButton.Text = Loc.GetString("secure-terminal-recall-button");
            }
        }
        else
        {
            RecallButton.Disabled = !showRecall;
            RecallButton.Text = Loc.GetString("secure-terminal-recall-button");
        }

        RequestButton.Disabled = !canRequest;
        if (_pendingConfirmId == proto.ID && canRequest)
        {
            RequestButton.Text = Loc.GetString("secure-terminal-request-button-confirm");
            RequestButton.StyleClasses.Add(StyleClass.Negative);
        }
        else
        {
            RequestButton.Text = Loc.GetString("secure-terminal-request-button");
            RequestButton.StyleClasses.Remove(StyleClass.Negative);
            _pendingConfirmId = null;
        }

        // Child action buttons (e.g. End GAMMA Alert nested under Code GAMMA)
        ChildActionsContainer.RemoveAllChildren();
        var childProtos = _protos.EnumeratePrototypes<SecureCommandTerminalRequestPrototype>()
            .Where(p => p.ParentId == proto.ID)
            .OrderBy(p => p.SortOrder);
        foreach (var child in childProtos)
        {
            var childAlertElapsed = (_timing.CurTime - state.AlertLevelSetAt).TotalMinutes;
            var childAvailable = !state.UsedOnce.Contains(child.ID)
                && !state.CoolingDown.ContainsKey(child.ID)
                && !(child.RequiresWarDeclared && !state.IsWarDeclared)
                && !(child.RequiresWarNotDeclared && state.IsWarDeclared)
                && !(child.RequiresAlertLevel != null && state.CurrentAlertLevel != child.RequiresAlertLevel)
                && !(child.RequiresAlertActiveMinutes > 0 && childAlertElapsed < child.RequiresAlertActiveMinutes)
                && state.Proposals.Find(p => p.RequestId == child.ID) == null;
            var childBtn = new Button
            {
                Text = Loc.GetString(child.Name),
                Disabled = !childAvailable,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2, 0, 0),
            };
            if (!childAvailable)
                childBtn.ModulateSelfOverride = Color.FromHex("#cc3333");
            var childId = child.ID;
            childBtn.OnPressed += _ =>
            {
                _selectedRequestId = childId;
                _pendingConfirmId = null;
                RebuildRequestList(_lastState!);
                RefreshRightPanel(_lastState!);
            };
            ChildActionsContainer.AddChild(childBtn);
        }

        // Auth section
        if (proposal == null)
        {
            AuthDescLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("secure-terminal-auth-waiting")));
            RebuildAuthorizationPreview(proto);
            AuthorizeButton.Disabled = true;
            DenyButton.Disabled = true;
        }
        else
        {
            AuthDescLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(
                Loc.GetString("secure-terminal-auth-desc")));
            if (proposal.Status == SecureTerminalProposalStatus.Activating)
                RebuildAuthorizedList(proposal);
            else
                RebuildAuthorizerList(proposal);

            AuthorizeButton.Disabled = proposal.Status != SecureTerminalProposalStatus.Pending;
            var vetoAvailable = proposal.Status == SecureTerminalProposalStatus.Activating
                && proto.VetoSchemes.Count > 0
                && proposal.ActivateAt > _timing.CurTime;
            DenyButton.Disabled = proposal.Status != SecureTerminalProposalStatus.Pending && !vetoAvailable;
        }
    }

    private void RebuildAuthorizedList(SecureTerminalProposalState proposal)
    {
        AuthorizerListContainer.RemoveAllChildren();

        var authorizedBy = string.Join(", ", proposal.AuthorizedBy.Select(authorizer =>
            string.IsNullOrEmpty(authorizer.Job)
                ? authorizer.Name
                : $"{authorizer.Name} ({authorizer.Job})"));
        var authorizedByLabel = new RichTextLabel
        {
            HorizontalExpand = true
        };
        authorizedByLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(
            $"{Loc.GetString("secure-terminal-authorized-by-label")} {authorizedBy}"));
        AuthorizerListContainer.AddChild(authorizedByLabel);

        if (proposal.VetoSchemes.Count > 0)
        {
            var vetoHeader = new RichTextLabel();
            vetoHeader.SetMessage(FormattedMessage.FromMarkupOrThrow(
                $"[bold]{Loc.GetString("secure-terminal-veto-label")}[/bold]"));
            AuthorizerListContainer.AddChild(vetoHeader);
            AddSchemeStates(proposal.VetoSchemes);
        }
    }

    private void RebuildAuthorizationPreview(SecureCommandTerminalRequestPrototype proto)
    {
        AuthorizerListContainer.RemoveAllChildren();

        foreach (var scheme in proto.AuthSchemes)
        {
            var schemeName = string.IsNullOrWhiteSpace(scheme.Name)
                ? scheme.Id
                : Loc.GetString(scheme.Name);
            var schemeHeader = new RichTextLabel();
            schemeHeader.SetMessage(FormattedMessage.FromMarkupOrThrow(
                $"[bold]{schemeName} — {scheme.Groups.Count}[/bold]"));
            AuthorizerListContainer.AddChild(schemeHeader);

            foreach (var group in scheme.Groups)
            {
                var label = new RichTextLabel();
                label.SetMessage(FormattedMessage.FromMarkupOrThrow(string.Join(" / ", group)));
                AuthorizerListContainer.AddChild(label);
            }
        }
    }

    private static string GetSalaryModifierNote(SecureCommandTerminalRequestPrototype proto)
    {
        var changes = proto.SalaryModifiers
            .Where(modifier => modifier.Change != 0)
            .Select(modifier => $"- {modifier.Source}: {modifier.Change * 100:+0.#;-0.#;0}%");
        var changeText = string.Join("\n", changes);
        return string.IsNullOrEmpty(changeText)
            ? string.Empty
            : $"\n{Loc.GetString("secure-terminal-salary-note")}\n{changeText}";
    }

    private void RebuildAuthorizerList(SecureTerminalProposalState proposal)
    {
        AuthorizerListContainer.RemoveAllChildren();

        AddSchemeStates(proposal.AuthSchemes);
        if (proposal.VetoSchemes.Count > 0)
        {
            var vetoHeader = new RichTextLabel();
            vetoHeader.SetMessage(FormattedMessage.FromMarkupOrThrow("[bold]Veto[/bold]"));
            AuthorizerListContainer.AddChild(vetoHeader);
            AddSchemeStates(proposal.VetoSchemes);
        }
    }

    private void AddSchemeStates(List<SecureTerminalAuthSchemeState> schemes)
    {
        foreach (var scheme in schemes)
        {
            var approvals = scheme.GroupsSatisfied.Count(satisfied => satisfied);
            var schemeName = string.IsNullOrWhiteSpace(scheme.Name)
                ? scheme.Id
                : Loc.GetString(scheme.Name);
            var schemeHeader = new RichTextLabel();
            schemeHeader.SetMessage(FormattedMessage.FromMarkupOrThrow(
                $"[bold]{schemeName} — {approvals} / {scheme.GroupLabels.Count}[/bold]"));
            AuthorizerListContainer.AddChild(schemeHeader);

            for (var i = 0; i < scheme.GroupLabels.Count; i++)
            {
                var satisfied = i < scheme.GroupsSatisfied.Count && scheme.GroupsSatisfied[i];
                var auth = satisfied && i < scheme.AuthorizedBy.Count ? scheme.AuthorizedBy[i] : default;

                string text;
                string color;
                if (satisfied && !string.IsNullOrEmpty(auth.Name))
                {
                    color = "green";
                    var jobPart = !string.IsNullOrEmpty(auth.Job)
                        ? $" ({auth.Job})"
                        : string.Empty;
                    text = $"\u25cf {auth.Name}{jobPart}";
                }
                else
                {
                    color = "red";
                    text = $"\u25cb {Loc.GetString("secure-terminal-awaiting-member", ("label", scheme.GroupLabels[i]))}";
                }

                var label = new RichTextLabel();
                label.SetMessage(FormattedMessage.FromMarkupOrThrow($"[color={color}]{text}[/color]"));
                AuthorizerListContainer.AddChild(label);
            }
        }
    }

    private void OnRequestPressed()
    {
        if (_selectedRequestId == null) return;

        // First click: turn red and ask for confirmation
        if (_pendingConfirmId != _selectedRequestId)
        {
            _pendingConfirmId = _selectedRequestId;
            RequestButton.Text = Loc.GetString("secure-terminal-request-button-confirm");
            RequestButton.StyleClasses.Add(StyleClass.Negative);
            return;
        }

        // Second click: execute
        _pendingConfirmId = null;
        RequestButton.Text = Loc.GetString("secure-terminal-request-button");
        RequestButton.StyleClasses.Remove(StyleClass.Negative);
        OnRequest?.Invoke(_selectedRequestId);
    }
}
