using Content.Client.Lobby;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using System.Linq;
using Content.Client.Sprite;
using Content.Shared.CCVar;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared._Starlight.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client._Starlight.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HumanoidProfileEditor : BoxContainer
    {
        private readonly IClientPreferencesManager _preferencesManager;
        private readonly IConfigurationManager _cfgManager;
        private readonly IEntityManager _entManager;
        private readonly IFileDialogManager _dialogManager;
        private readonly IPlayerManager _playerManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly MarkingManager _markingManager;
        private readonly JobRequirementsManager _requirements;

        private readonly SpriteSystem _sprite;

        private int _maxNameLength;

        public event Action? Save;

        /// <summary>
        /// Track the state of the ShowClothes button to use for the profile preview.
        /// </summary>
        public bool ShouldShowClothes => ShowClothes.Pressed;

        public int? CharacterSlot;

        public HumanoidCharacterProfile? Profile;

        /// <summary>
        /// The last profile loaded from preferences. Used for dirty-state checks and reset.
        /// </summary>
        private HumanoidCharacterProfile? _savedProfile;

        private Direction _previewRotation = Direction.North;

        private bool _isDirty;

        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;

                _isDirty = value;
                UpdateSaveButton();
            }
        }

        private readonly ISawmill _sawmill;

        public HumanoidProfileEditor(
            IClientPreferencesManager preferencesManager,
            IConfigurationManager configurationManager,
            IEntityManager entManager,
            IFileDialogManager dialogManager,
            ILogManager logManager,
            IPlayerManager playerManager,
            IPrototypeManager prototypeManager,
            IResourceManager resManager,
            JobRequirementsManager requirements,
            MarkingManager markings)
        {
            RobustXamlLoader.Load(this);
            _sawmill = logManager.GetSawmill("profile.editor");
            _cfgManager = configurationManager;
            _entManager = entManager;
            _dialogManager = dialogManager;
            _playerManager = playerManager;
            _prototypeManager = prototypeManager;
            _markingManager = markings;
            _preferencesManager = preferencesManager;
            _requirements = requirements;
            _sprite = _entManager.System<SpriteSystem>();

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _allowFlavorText = _cfgManager.GetCVar(CCVars.FlavorText);
            _allowCharacterSecrets = _cfgManager.GetCVar(StarlightCCVars.ICSecrets);
            _allowExploitables = _cfgManager.GetCVar(StarlightCCVars.ExploitableSecrets);
            _allowRPNotes = _cfgManager.GetCVar(StarlightCCVars.OOCNotes);

            OOCInfoTab.Visible = _allowRPNotes;
            ICInfoTab.Visible = _allowFlavorText || _allowExploitables || _allowCharacterSecrets;

            ImportButton.OnPressed += _ => ImportProfile();
            ExportButton.OnPressed += _ => ExportProfile();
            ExportImageButton.OnPressed += _ => ExportImage();
            OpenImagesButton.OnPressed += _ => resManager.UserData.OpenOsWindow(ContentSpriteSystem.Exports);
            ResetButton.OnPressed += _ => ResetToDefault();
            SaveButton.OnPressed += _ => Save?.Invoke();

            Traits.OnTraitsChanged += OnTraitsSelectionChanged;

            Antags.OnAntagsChanged += OnAntagsSelectionChanged;
            Antags.OnLoadoutPressed += OnAntagLoadoutPressed;

            NameEdit.OnTextChanged += args => SetName(args.Text);
            NameEdit.IsValid = args => args.Length <= _maxNameLength;
            NameRandomize.OnPressed += _ => RandomizeName();
            RandomizeEverythingButton.OnPressed += _ => RandomizeEverything();
            WarningLabel.SetMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");

            CCustomSpecieNameEdit.OnTextChanged += args => SetCustomSpecieName(args.Text);

            SexButton.OnItemSelected += args =>
            {
                SexButton.SelectId(args.Id);
                SetSex((Sex) args.Id);
            };

            AgeEdit.OnTextChanged += args =>
            {
                if (int.TryParse(args.Text, out var newAge))
                    SetAge(newAge);
            };

            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int) Gender.Male);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int) Gender.Female);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int) Gender.Epicene);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int) Gender.Neuter);

            PronounsButton.OnItemSelected += args =>
            {
                PronounsButton.SelectId(args.Id);
                SetGender((Gender) args.Id);
            };

            RefreshSpecies();

            SpeciesButton.OnItemSelected += args =>
            {
                SpeciesButton.SelectId(args.Id);
                SetSpecies(_species[args.Id].ID);
                UpdateHairPickers();
                OnSkinColorOnValueChanged();
                UpdateCustomSpecieNameEdit();
            };

            UpdateSubspecies();
            SubspeciesButton.OnItemSelected += args =>
            {
                SubspeciesButton.SelectId(args.Id);
                SetSpecies(_subspecies[args.Id].ID);
                UpdateHairPickers();
                UpdateCustomSpecieNameEdit();
            };

            UpdateSizeControls();

            WidthSlider.OnValueChanged += args => SetCharacterWidth(args.Value);
            HeightSlider.OnValueChanged += args => SetCharacterHeight(args.Value);

            WidthResetButton.OnPressed += _ =>
            {
                if (Profile is null)
                    return;

                if (_prototypeManager.TryIndex<SpeciesPrototype>(Profile.Species, out var speciesPrototype))
                    WidthSlider.Value = speciesPrototype.DefaultWidth;
            };

            HeightResetButton.OnPressed += _ =>
            {
                if (Profile is null)
                    return;

                if (_prototypeManager.TryIndex<SpeciesPrototype>(Profile.Species, out var speciesPrototype))
                    HeightSlider.Value = speciesPrototype.DefaultHeight;
            };

            Skin.OnValueChanged += _ => OnSkinColorOnValueChanged();

            RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders());
            _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;
            _rgbSkinColorSelector.OnColorChanged += _ => OnSkinColorOnValueChanged();

            HairStylePicker.OnMarkingSelect += newStyle =>
            {
                if (Profile is null)
                    return;

                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithHairStyleName(newStyle.id));
                ReloadPreview();
            };

            HairStylePicker.OnColorChanged += newColor =>
            {
                if (Profile is null)
                    return;

                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithHairColor(newColor.marking.MarkingColors[0]));
                UpdateCMarkingsHair();
                ReloadPreview();
            };

            HairStylePicker.OnGlowingChanged += newColor =>
            {
                if (Profile is null)
                    return;

                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithHairGlowing(newColor.marking.IsGlowing));
                UpdateCMarkingsHair();
                ReloadPreview();
            };

            FacialHairPicker.OnMarkingSelect += newStyle =>
            {
                if (Profile is null)
                    return;

                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithFacialHairStyleName(newStyle.id));
                ReloadPreview();
            };

            FacialHairPicker.OnColorChanged += newColor =>
            {
                if (Profile is null)
                    return;

                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithFacialHairColor(newColor.marking.MarkingColors[0]));
                UpdateCMarkingsFacialHair();
                ReloadPreview();
            };

            FacialHairPicker.OnGlowingChanged += newColor =>
            {
                if (Profile is null)
                    return;

                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithFacialHairGlowing(newColor.marking.IsGlowing));
                UpdateCMarkingsFacialHair();
                ReloadPreview();
            };

            HairStylePicker.OnSlotRemove += _ =>
            {
                if (Profile is null)
                    return;

                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithHairStyleName(HairStyles.DefaultHairStyle));
                UpdateHairPickers();
                UpdateCMarkingsHair();
                ReloadPreview();
            };

            FacialHairPicker.OnSlotRemove += _ =>
            {
                if (Profile is null)
                    return;

                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithFacialHairStyleName(HairStyles.DefaultFacialHairStyle));
                UpdateHairPickers();
                UpdateCMarkingsFacialHair();
                ReloadPreview();
            };

            HairStylePicker.OnSlotAdd += delegate
            {
                if (Profile is null)
                    return;

                var hair = _markingManager.MarkingsByCategoryAndSpecies(MarkingCategories.Hair, Profile.Species).Keys
                    .FirstOrDefault();

                if (string.IsNullOrEmpty(hair))
                    return;

                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithHairStyleName(hair));

                UpdateHairPickers();
                UpdateCMarkingsHair();
                ReloadPreview();
            };

            FacialHairPicker.OnSlotAdd += delegate
            {
                if (Profile is null)
                    return;

                var hair = _markingManager.MarkingsByCategoryAndSpecies(MarkingCategories.FacialHair, Profile.Species).Keys
                    .FirstOrDefault();

                if (string.IsNullOrEmpty(hair))
                    return;

                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithFacialHairStyleName(hair));

                UpdateHairPickers();
                UpdateCMarkingsFacialHair();
                ReloadPreview();
            };

            foreach (var value in Enum.GetValues<SpawnPriorityPreference>())
            {
                SpawnPriorityButton.AddItem(
                    Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{value.ToString().ToLower()}"),
                    (int) value);
            }

            SpawnPriorityButton.OnItemSelected += args =>
            {
                SpawnPriorityButton.SelectId(args.Id);
                SetSpawnPriority((SpawnPriorityPreference) args.Id);
            };

            EyeColorPicker.OnEyeColorPicked += newColor =>
            {
                if (Profile is null)
                    return;

                Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithEyeColor(newColor));
                Markings.CurrentEyeColor = Profile.Appearance.EyeColor;
                ReloadProfilePreview();
            };

            EyeColorPicker.OnGlowingChanged += newGlow =>
            {
                if (Profile is null)
                    return;

                Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithEyeGlowing(newGlow));
                Markings.CurrentEyeColor = Profile.Appearance.EyeColor;
                ReloadProfilePreview();
            };

            RefreshAntags();
            RefreshJobs();

            Markings.OnMarkingAdded += OnMarkingChange;
            Markings.OnMarkingRemoved += OnMarkingChange;
            Markings.OnMarkingColorChange += OnMarkingChange;
            Markings.OnMarkingRankChange += OnMarkingChange;

            Cybernetics.OnCyberneticsUpdated += OnCyberneticsUpdated;

            SpriteView.Initialize(_preferencesManager, _prototypeManager, _playerManager);

            SpriteRotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCw();
                SetPreviewRotation(_previewRotation);
            };

            SpriteRotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCcw();
                SetPreviewRotation(_previewRotation);
            };

            ShowClothes.OnToggled += _ => ReloadPreview();
            SpeciesInfoButton.OnPressed += OnSpeciesInfoButtonPressed;

            UpdateSpeciesGuidebookIcon();
            InitializeVoiceSelectors();
            SetupTabs();
            _recordsTab = CreateRecordEditorTab();
            SetupInfoEditors();
            RefreshCharacterInfo();
            IsDirty = false;
        }

        private void SetDirty()
        {
            if (Profile == null || _savedProfile?.MemberwiseEquals(Profile) == true)
            {
                IsDirty = false;
                return;
            }

            IsDirty = true;
        }

        private void ReloadPreview()
        {
            if (Profile == null)
                return;

            SpriteView.LoadPreview(Profile, JobOverride, ShowClothes.Pressed);
            SetDirty();
        }

        public void ResetToDefault()
        {
            SetProfile(_savedProfile, CharacterSlot);
        }

        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            SpriteView.Initialize(_preferencesManager, _prototypeManager, _playerManager);
            Profile = profile?.Clone();
            CharacterSlot = slot;
            IsDirty = false;
            JobOverride = null;
            AntagOverride = null;

            UpdateNameEdit();
            UpdateSubspecies();
            UpdateCustomSpecieNameEdit();
            UpdateCharacterInfoEditorText();
            UpdateSexControls();
            UpdateGenderControls();
            UpdateSizeControls();
            UpdateSkinColor();
            UpdateSpawnPriorityControls();
            UpdateAgeEdit();
            UpdateEyePickers();
            UpdateSaveButton();
            UpdateMarkings();
            UpdateHairPickers();
            UpdateCMarkingsHair();
            UpdateCMarkingsFacialHair();
            UpdateVoicesControls();
            UpdateSiliconVoicesControls();
            UpdateCybernetics();
            UpdateSpeciesLoadout();
            UpdateTraitsSelection();
            RefreshAntags();
            RefreshJobs();
            RefreshLoadouts();
            RefreshSpecies();
            _recordsTab.Update(Profile);
            RefreshCharacterInfo();
            ReloadPreview();
        }

        public void SetProfile(int slot)
        {
            if (_preferencesManager.Preferences == null)
                return;

            if (!_preferencesManager.Preferences.TryGetHumanoidInSlot(slot, out var humanoid))
                return;

            _savedProfile = humanoid.Clone();
            SetProfile(humanoid, slot);
        }

        private void ReloadProfilePreview()
        {
            if (Profile == null)
                return;

            SpriteView.ReloadProfilePreview(Profile);
            SetDirty();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ReloadPreview();
        }

        private void UpdateSaveButton()
        {
            SaveButton.Disabled = Profile is null || !IsDirty;
            ResetButton.Disabled = Profile is null || !IsDirty;
        }

        private void SetPreviewRotation(Direction direction)
        {
            SpriteView.OverrideDirection = (Direction) ((int) direction % 4 * 2);
        }
    }
}
