using System.Linq;
using Content.Shared.Humanoid;
using Content.Shared._Starlight.TextToSpeech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class VoiceSelectorWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public List<VoicePrototype> Voices { get; set; } = [];

    public Action<VoicePrototype>? OnVoiceSelected;

    public Action? OnPreviewRequested;

    public VoicePrototype? CurrentVoice { get; private set; } = null;

    private readonly VoiceTagTaxonomy _taxonomy;

    private Sex? _sexFilter = null;
    private VoicePitch? _pitchFilter = null;
    private VoiceTag? _tagFilter = null;

    public VoiceSelectorWindow(List<VoicePrototype> voices)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _taxonomy = new VoiceTagTaxonomy(voices, _prototypeManager);

        VoiceList.OnItemSelected += OnItemSelected;

        UpdateVoices(voices);

        // Populate GenderFilter
        GenderFilter.AddItem(Loc.GetString("voice-selector-gender-all"));
        int genderIndex = 1;
        foreach (var sex in Enum.GetValues<Sex>())
        {
            var locKey = sex switch
            {
                Sex.Male => "voice-selector-gender-masculine",
                Sex.Female => "voice-selector-gender-feminine",
                _ => "voice-selector-gender-neutral"
            };
            GenderFilter.AddItem(Loc.GetString(locKey), genderIndex);
            GenderFilter.SetItemMetadata(genderIndex, sex);
            genderIndex++;
        }
        GenderFilter.OnItemSelected += args => OnFilterSelectedNullable<Sex>(GenderFilter, args.Id, v => _sexFilter = v);

        // Populate PitchFilter
        PitchFilter.AddItem(Loc.GetString("voice-selector-pitch-all"));
        int pitchIndex = 1;
        foreach (var pitch in Enum.GetValues<VoicePitch>())
        {
            PitchFilter.AddItem(Loc.GetString($"voice-selector-pitch-{pitch.ToString().ToLowerInvariant()}"), pitchIndex);
            PitchFilter.SetItemMetadata(pitchIndex, pitch);
            pitchIndex++;
        }
        PitchFilter.OnItemSelected += args => OnFilterSelectedNullable<VoicePitch>(PitchFilter, args.Id, v => _pitchFilter = v);

        // Populate TagFilter
        TagFilter.AddItem(Loc.GetString("voice-selector-tag-all"));
        int tagIndex = 1;
        foreach (var tag in _taxonomy.CachedTags)
        {
            TagFilter.AddItem(tag.ToDisplayName(), tagIndex);
            TagFilter.SetItemMetadata(tagIndex, tag);
            tagIndex++;
        }
        TagFilter.OnItemSelected += args => OnFilterSelectedNullable<VoiceTag>(TagFilter, args.Id, v => _tagFilter = v);

        SearchLine.OnTextChanged += _ => FilterAndUpdateVoices();
        PreviewButton.OnPressed += _ => OnPreviewRequested?.Invoke();
    }

    private void OnFilterSelected<T>(OptionButton button, int id, Action<T?> setter) where T : class
    {
        button.SelectId(id);
        var metadata = button.GetItemMetadata(id);
        setter(metadata as T);
        FilterAndUpdateVoices();
    }

    private void OnFilterSelectedNullable<T>(OptionButton button, int id, Action<T?> setter) where T : struct
    {
        button.SelectId(id);
        var metadata = button.GetItemMetadata(id);
        if (metadata is T result)
            setter(result);
        else
            setter(null);
        FilterAndUpdateVoices();
    }

    private void OnItemSelected(ItemList.ItemListSelectedEventArgs obj)
    {
        if (obj.ItemList.TryGetValue(obj.ItemIndex, out var item) && item.Metadata is VoicePrototype voice)
        {
            OnVoiceSelected?.Invoke(voice);
            CurrentVoice = voice;
            CurrentVoiceLabel.Text = Loc.GetString("voice-selector-current-voice", ("voice", Loc.GetString(voice.Name)));
        }
    }

    public void FilterAndUpdateVoices()
    {
        var searchText = SearchLine.Text.Trim();
        var hasSearch = !string.IsNullOrWhiteSpace(searchText);
        var searchLower = hasSearch ? searchText.ToLowerInvariant() : "";

        var voices = Voices.Where(v =>
        {
            var mappedTags = _taxonomy.ResolvePresentingTags(v);
            return (_sexFilter == null || v.Sex == _sexFilter) &&
                   (_pitchFilter == null || v.Pitch == _pitchFilter) &&
                   (_tagFilter == null || mappedTags.Contains(_tagFilter.Value)) &&
                   (!hasSearch ||
                    Loc.GetString(v.Name).Contains(searchText, StringComparison.InvariantCultureIgnoreCase) ||
                    mappedTags.Any(t => t.Value.Contains(searchLower)));
        }).ToList();
        UpdateVoices(voices, updateList: false);
    }

    public void UpdateVoices(List<VoicePrototype> voices, bool updateList = true, bool updateVoice = true)
    {
        if (updateList)
        {
            Voices.Clear();
            Voices.AddRange(voices);
        }

        var displayVoices = voices.OrderBy(v => Loc.GetString(v.Name)).ToList();

        VoiceList.Clear();
        foreach (var voice in displayVoices)
        {
            var sexLoc = voice.Sex switch
            {
                Sex.Male => Loc.GetString("voice-selector-gender-masculine"),
                Sex.Female => Loc.GetString("voice-selector-gender-feminine"),
                _ => Loc.GetString("voice-selector-gender-neutral")
            };
            VoiceList.AddItem($"[{sexLoc}] {Loc.GetString(voice.Name)}", metadata: voice);
        }

        if (updateVoice && CurrentVoice != null)
            SelectVoice(CurrentVoice);
    }

    public void SelectVoice(VoicePrototype voice)
    {
        var item = VoiceList.Where(x => x.Metadata is VoicePrototype voice1 && voice1.ID == voice.ID);
        if (item.Any())
            item.First().Selected = true;

        CurrentVoice = voice;

        CurrentVoiceLabel.Text = Loc.GetString("voice-selector-current-voice", ("voice", Loc.GetString(voice.Name)));
    }
}
