using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.StatusIcon;
using Content.Shared.Tag;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using static Content.Shared._Starlight.Access.Components.JobIdentityConsoleComponent;

namespace Content.Client._Starlight.Access.UI;

[GenerateTypedNameReferences]
public sealed partial class JobIdentityConsoleWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntitySystemManager _entitySystem = default!;
    [Dependency] private IConfigurationManager _cfgManager = default!;
    private readonly SpriteSystem _spriteSystem;

    private const int JobIconColumnCount = 10;

    private JobIdentityConsoleBoundUserInterface? _owner;
    private readonly int _maxIdJobLength;

    private string? _lastJobTitle;
    private ProtoId<JobIconPrototype> _currentJobIcon = "JobIconUnknown";
    private HashSet<ProtoId<TagPrototype>> _requiredTags = new();

    public JobIdentityConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();

        _maxIdJobLength = _cfgManager.GetCVar(CCVars.MaxIdJobLength);

        JobTitleLineEdit.OnTextEntered += _ => SubmitData();
        JobTitleLineEdit.IsValid = s => s.Length <= _maxIdJobLength;
        JobTitleLineEdit.OnTextChanged += _ =>
        {
            JobTitleSaveButton.Disabled = JobTitleLineEdit.Text == _lastJobTitle;
        };
        JobTitleSaveButton.OnPressed += _ => SubmitData();
    }

    public void Initialize(JobIdentityConsoleBoundUserInterface owner, HashSet<ProtoId<TagPrototype>> requiredTags)
    {
        _owner = owner;
        _requiredTags = requiredTags;
    }

    public void UpdateState(JobIdentityConsoleBoundUserInterfaceState state)
    {
        PrivilegedIdButton.Text = state.IsPrivilegedIdPresent
            ? Loc.GetString("id-card-console-window-eject-button")
            : Loc.GetString("id-card-console-window-insert-button");
        PrivilegedIdLabel.Text = state.PrivilegedIdName;

        TargetIdButton.Text = state.IsTargetIdPresent
            ? Loc.GetString("id-card-console-window-eject-button")
            : Loc.GetString("id-card-console-window-insert-button");
        TargetIdLabel.Text = state.TargetIdName;

        var interfaceEnabled =
            state.IsPrivilegedIdPresent && state.IsPrivilegedIdAuthorized && state.IsTargetIdPresent;

        var jobTitleDirty = _lastJobTitle != null && JobTitleLineEdit.Text != state.TargetIdJobTitle;

        JobTitleLabel.Modulate = interfaceEnabled ? Color.White : Color.Gray;
        JobTitleLineEdit.Editable = interfaceEnabled;
        if (!jobTitleDirty)
            JobTitleLineEdit.Text = state.TargetIdJobTitle ?? string.Empty;

        JobTitleSaveButton.Disabled = !interfaceEnabled || !jobTitleDirty;

        _lastJobTitle = state.TargetIdJobTitle;
        _currentJobIcon = state.TargetIdJobIcon ?? _currentJobIcon;

        IconGridLabel.Modulate = interfaceEnabled ? Color.White : Color.Gray;
        PopulateIcons(interfaceEnabled);
    }

    private void PopulateIcons(bool enabled)
    {
        IconGrid.RemoveAllChildren();

        var jobIconButtonGroup = new ButtonGroup();
        var i = 0;
        var icons = _prototypeManager.EnumeratePrototypes<JobIconPrototype>()
            .Where(icon => icon.AllowSelection && icon.Tags.Overlaps(_requiredTags))
            .ToList();
        icons.Sort((x, y) => string.Compare(x.LocalizedJobName, y.LocalizedJobName, StringComparison.CurrentCulture));

        foreach (var jobIcon in icons)
        {
            var styleBase = StyleClass.ButtonOpenBoth;
            var modulo = i % JobIconColumnCount;
            if (modulo == 0)
                styleBase = StyleClass.ButtonOpenRight;
            else if (modulo == JobIconColumnCount - 1)
                styleBase = StyleClass.ButtonOpenLeft;

            var jobIconButton = new Button
            {
                Access = AccessLevel.Public,
                StyleClasses = { styleBase },
                MaxSize = new Vector2(42, 28),
                Group = jobIconButtonGroup,
                Pressed = _currentJobIcon == jobIcon.ID,
                Disabled = !enabled,
                ToolTip = jobIcon.LocalizedJobName,
            };

            var jobIconTexture = new TextureRect
            {
                Texture = _spriteSystem.Frame0(jobIcon.Icon),
                TextureScale = new Vector2(2.5f, 2.5f),
                Stretch = TextureRect.StretchMode.KeepCentered,
            };

            jobIconButton.AddChild(jobIconTexture);
            jobIconButton.OnPressed += _ =>
            {
                _currentJobIcon = jobIcon.ID;
                _owner?.SubmitData(JobTitleLineEdit.Text, _currentJobIcon);
            };
            IconGrid.AddChild(jobIconButton);

            i++;
        }
    }

    private void SubmitData()
    {
        // Should no icon be selected the existing icon will be retained - prevents issues in the case of a title only submit.
        _owner?.SubmitData(JobTitleLineEdit.Text, null);
    }
}
