// Starlight-edit
using Content.Client.UserInterface.Controls;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWindow : FancyWindow
{
    public HealthAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
    }
    // Starlight-start: Printable health reports.
    public event Action? PrintReportPressed
    {
        add => HealthAnalyzer.PrintReportPressed += value;
        remove => HealthAnalyzer.PrintReportPressed -= value;
    }

    // Starlight-end

    public void Populate(HealthAnalyzerScannedUserMessage msg)
    {
        HealthAnalyzer.Populate(msg.State);
    }
}
