using System.Linq;
using Content.Client.Lobby;
using Content.Shared._Starlight.GhostTheme;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Client.GameTicking.Managers;
using Content.Shared._Starlight.CCVar;
using Robust.Client.UserInterface;
using Robust.Shared.Configuration;

namespace Content.Client._Starlight.GhostTheme;

[GenerateTypedNameReferences]
public sealed partial class GhostThemeWindow : DefaultWindow
{
    private readonly IClientPreferencesManager _preferencesManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntitySystemManager _entitySystem = default!;
    [Dependency] private IConfigurationManager _conf = default!;

    private readonly ClientGameTicker _gameTicker;
    private readonly SpriteSystem _sprites;

    public string SelectedTheme = "None";

    public event Action<string>? SelectTheme;

    public event Action<Color>? SelectColor;

    public Color _selectedColor = Color.White;

    public HashSet<string> _availableThemes = [];
    private string _searchFilter = "";
    private int _lastTabBeforeSearch = -1;

    public GhostThemeWindow(IClientPreferencesManager preferencesManager)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _preferencesManager = preferencesManager;
        _sprites = _entitySystem.GetEntitySystem<SpriteSystem>();
        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();

        Search.OnTextTyped += OnSearchTyped;
        Search.OnTextRemoved += OnSearchRemoved;

        ReloadGhostThemes();
        CategoryTabs.CurrentTab = 1; // this shouldn't cause issues considering i know other tabs exist :3
        RefreshUI();
    }

    private void OnSearchTyped(GUITextEnteredEventArgs obj)
    {
        _searchFilter = Search.Text.Trim().ToLowerInvariant();
        FilterGhostThemes(_searchFilter);
    }

    private void OnSearchRemoved(LineEdit.LineEditTextRemovedEventArgs args)
    {
        _searchFilter = args.NewText.Trim().ToLowerInvariant();
        FilterGhostThemes(_searchFilter);
    }

    private void FilterGhostThemes(string searchText)
    {
        var searchTerms = searchText.Split(',', StringSplitOptions.RemoveEmptyEntries)
                                    .Select(term => term.Trim())
                                    .Where(term => !string.IsNullOrWhiteSpace(term))
                                    .ToList();

        if (searchTerms.Count > 0)
        {
            for (var i = 0; i < CategoryTabs.ChildCount; i++)
                CategoryTabs.SetTabVisible(i, i == 0);
            if(_lastTabBeforeSearch == -1) _lastTabBeforeSearch = CategoryTabs.CurrentTab;
            CategoryTabs.CurrentTab = 0;
        }
        else
        {
            for (var i = 0; i < CategoryTabs.ChildCount; i++)
                CategoryTabs.SetTabVisible(i, i != 0);
            CategoryTabs.CurrentTab = _lastTabBeforeSearch;
            _lastTabBeforeSearch = -1;
        }
        CategoryTabs.InvalidateArrange();

        foreach (var child in CategoryTabs.GetChild(0).GetChild(0).Children) // First tab is always filter tab.
        {
            if (child is GhostPicker ghostPicker)
            {
                var descriptionText = ghostPicker.DescriptionLabel?.Text?.ToLowerInvariant();

                ghostPicker.Visible = searchTerms.Count == 0 || searchTerms.Any(term => descriptionText?.Contains(term) == true);
            }
        }
    }

    public void ReloadGhostThemes()
    {
        CategoryTabs.RemoveAllChildren();
        // GhostThemesContainer.RemoveAllChildren();

        if (!_preferencesManager.ServerDataLoaded)
            return;

        List<GhostThemePrototype> themes = new();
        List<GhostThemeCategoryPrototype> categories = new();
        Dictionary<GhostThemePrototype, GhostThemeCategoryPrototype> sorted = new();
        Dictionary<GhostThemeCategoryPrototype, ScrollContainer> categoryTabsDict = new();

        // Collect all themes, sort alphabetically.
        themes.AddRange(_prototypeManager.EnumeratePrototypes<GhostThemePrototype>());
        themes.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.Ordinal));

        // Add category tabs, sort by priority.
        categories.AddRange(_prototypeManager.EnumeratePrototypes<GhostThemeCategoryPrototype>());
        categories = categories.OrderBy(category => category.Priority).ToList();

        // Find the designated filter category and take it out of list, make tab for it.
        var filterCategory = categories.First(category => category.IsFilter);
        categories.Remove(filterCategory);
        var filterTab = new ScrollContainer
        {
            Name = filterCategory.Name,
            Visible = false
        };
        var filterThemeBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            VerticalExpand = true,
        };
        filterTab.AddChild(filterThemeBox);
        CategoryTabs.AddChild(filterTab);
        CategoryTabs.SetTabVisible(0, false);

        // Associate theme to category to avoid needing to do unnecessary loops later
        foreach (var theme in themes)
        {
            var category = categories.FirstOrDefault(category => category.ID == theme.Category);
            if (category is null) continue;
            sorted.Add(theme, category);
        }

        // Add tab buttons for each category, populate their lists.
        foreach (var (theme, category) in sorted)
        {
            if (theme.Private && !_availableThemes.Contains(theme.ID))
                continue;

            BoxContainer themeBox;

            if (!categoryTabsDict.TryGetValue(category, out var tab))
            {
                tab = new ScrollContainer() { Name = category.Name, };
                themeBox = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    VerticalExpand = true,
                };
                tab.AddChild(themeBox);
                categoryTabsDict.Add(category, tab);
            }
            else themeBox = (BoxContainer)tab.GetChild(0);

            var ghostPicker = new GhostPicker(_sprites, theme.SpriteSpecifier.Sprite, theme.Name,
                !_availableThemes.Contains(theme.ID));
            var ghostPickerFilter = new GhostPicker(_sprites, theme.SpriteSpecifier.Sprite, theme.Name,
                !_availableThemes.Contains(theme.ID));
            themeBox.AddChild(ghostPicker);
            filterThemeBox.AddChild(ghostPickerFilter);

            var tooltip = string.Join(", ", theme.Requirements.Select(x => x.GetRequirementDescription()));
            ghostPicker.ToolTip = tooltip;
            ghostPickerFilter.ToolTip = tooltip;

            if (_availableThemes.Contains(theme.ID))
            {
                ghostPicker.OnPressed += args =>
                {
                    SelectedTheme = theme.ID;
                    RefreshUI();
                };
                ghostPickerFilter.OnPressed += args =>
                {
                    SelectedTheme = theme.ID;
                    RefreshUI();
                };
            }
        }

        // Hide tabs with no unlocks that are set to do so by removing from dictionary entirely
        if (!_conf.GetCVar(StarlightCCVars.ForceTestersTab)) categoryTabsDict = categoryTabsDict
            .Where(category =>
                !(category.Key.HideIfNoUnlocks &&
                  category.Value.GetChild(0).Children
                      .OfType<GhostPicker>()
                      .All(x => x.Disabled)))
            .ToDictionary();

        // Actually append the tabs in the order of categories list
        foreach (var category in categories.Where(category => categoryTabsDict.ContainsKey(category)))
            CategoryTabs.AddChild(categoryTabsDict[category]);
    }

    public void UpdateThemes(HashSet<string> AvailableThemes)
    {
        _availableThemes = AvailableThemes;

        ReloadGhostThemes();
        RefreshUI();
    }

    public void RefreshUI()
    {
        GhostThemeDescriptionContainer.RemoveAllChildren();

        _selectedColor = Color.White;

        if (!_prototypeManager.TryIndex<GhostThemePrototype>(SelectedTheme, out var ghostThemePrototype))
            return;

        var ghostDescription = new GhostDescription(_sprites,
                ghostThemePrototype.SpriteSpecifier.Sprite,
                ghostThemePrototype.Name,
                ghostThemePrototype.Description,
                ghostThemePrototype.Colorizeable);

        ghostDescription.OnColorSelected += color
            => _selectedColor = color;

        ghostDescription.OnThemeSelected += () =>
        {
            SelectTheme?.Invoke(ghostThemePrototype.ID);
            SelectColor?.Invoke(_selectedColor);
        };

        GhostThemeDescriptionContainer.AddChild(ghostDescription);
    }
}
