- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobRoboticist

- type: playTimeTracker
  id: JobDutyOfficer

- type: playTimeTracker
  id: JobMagistrate

- type: playTimeTracker
  id: JobNanoTrasenRepresentative

- type: playTimeTracker
  id: JobIAA

- type: playTimeTracker
  id: JobCentralCommandOperator

- type: playTimeTracker
  id: JobBlueShield

- type: playTimeTracker
  id: JobConsortiumBlueShield

- type: playTimeTracker
  id: JobMiningSpecialist

- type: playTimeTracker
  id: JobSurgeon
  
- type: playTimeTracker
  id: JobMailTech

- type: playTimeTracker
  id: JobSalvageLead

- type: playTimeTracker
  id: JobNTSF
  
- type: playTimeTracker
  id: JobDecimus
  
- type: playTimeTracker
  id: JobBoxer

- type: playTimeTracker
  id: JobZookeeper

- type: playTimeTracker
  id: JobNanotrasenCareerTrainer

# Other ghosts

- type: playTimeTracker
  id: GhostPAI

- type: playTimeTracker
  id: GhostCritterHarmless

- type: playTimeTracker
  id: GhostBotHarmless

- type: playTimeTracker
  id: GhostNecktie

- type: playTimeTracker
  id: GhostSkeleton

- type: playTimeTracker
  id: GhostXeno

- type: playTimeTracker
  id: Observer
