- type: Salaries
  id: standart
  jobs:
    Captain: 150
    HeadOfPersonnel: 130
    HeadOfSecurity: 145
    ChiefEngineer: 140
    ResearchDirector: 130
    ChiefMedicalOfficer: 135
    Quartermaster: 120

    BlueShield: 110
    NanoTrasenRepresentative: 165
    Magistrate: 176
    NanotrasenCareerTrainer: 150
    IAA: 76

    Chemist: 90
    Psychologist: 76
    Paramedic: 50
    MedicalDoctor: 58
    MedicalIntern: 23
    Surgeon: 90

    AtmosphericTechnician: 90
    StationEngineer: 54
    TechnicalAssistant: 23

    Warden: 90
    Detective: 80
    Brigmedic: 73
    DutyOfficer: 70
    SecurityOfficer: 64
    SecurityCadet: 23

    StationAi: 149
    Borg: 85

    AssistantManager: 60
    Chaplain: 50
    Chef: 50
    Janitor: 30
    Botanist: 50
    Lawyer: 55
    Librarian: 50
    Musician: 40
    Bartender: 50
    Mime: 30
    Clown: 30
    ServiceWorker: 23
    Performer: 23
    Reporter: 46
    Assistant: 15
    Boxer: 23

    Scientist: 65
    Roboticist: 58
    ResearchAssistant: 23

    SalvageLead: 75
    SalvageMedic: 70
    SalvageSpecialist: 60
    MiningSpecialist: 60
    CargoTechnician: 45
    MailTech: 55

    Visitor: 0
    Prisoner: 0
    StirStir: 0

  sender:
    Captain: "Central Administrative Division"
    HeadOfPersonnel: "Central Administrative Division"
    HeadOfSecurity: "Central Administrative Division"
    ChiefEngineer: "Central Administrative Division"
    ResearchDirector: "Central Administrative Division"
    ChiefMedicalOfficer: "Central Administrative Division"
    Quartermaster: "Central Administrative Division"

    BlueShield: "NanoTrasen"
    NanoTrasenRepresentative: "NanoTrasen"
    Magistrate: "NanoTrasen"
    NanotrasenCareerTrainer: "NanoTrasen"
    IAA: "NanoTrasen"

    Chemist: "Central Medical Division"
    Psychologist: "Central Medical Division"
    Paramedic: "Central Medical Division"
    MedicalDoctor: "Central Medical Division"
    MedicalIntern: "Central Medical Division"
    Surgeon: "Central Medical Division"

    AtmosphericTechnician: "Central Engineering Division"
    StationEngineer: "Central Engineering Division"
    TechnicalAssistant: "Central Engineering Division"

    Warden: "Central Security Division"
    Detective: "Central Security Division"
    Brigmedic: "Central Security Division"
    DutyOfficer: "Central Security Division"
    SecurityOfficer: "Central Security Division"
    SecurityCadet: "Central Security Division"

    StationAi: "NanoTrasen"
    Borg: "NanoTrasen"

    AssistantManager: "Central Domestic Division"
    Chaplain: "Central Domestic Division"
    Chef: "Central Domestic Division"
    Janitor: "Central Domestic Division"
    Botanist: "Central Domestic Division"
    Lawyer: "Central Domestic Division"
    Librarian: "Central Domestic Division"
    Musician: "Central Domestic Division"
    Bartender: "Central Domestic Division"
    Mime: "Central Domestic Division"
    Clown: "Central Domestic Division"
    ServiceWorker: "Central Domestic Division"
    Performer: "Central Domestic Division"
    Reporter: "Central Domestic Division"
    Assistant: "Central Domestic Division"
    Boxer: "Central Domestic Division"

    Scientist: "Central Research Division"
    Roboticist: "Central Research Division"
    ResearchAssistant: "Central Research Division"

    SalvageLead: "Interstellar Trade Guild"
    SalvageMedic: "Interstellar Trade Guild"
    SalvageSpecialist: "Interstellar Trade Guild"
    MiningSpecialist: "Central Cargo Division"
    CargoTechnician: "Central Cargo Division"
    MailTech: "Central Cargo Division"

    Visitor: "private account"
    Prisoner: "private account"
    StirStir: "private account"


- type: SalaryRoleBonus
  id: BlackOpsBonus
  roles:
  - 1294130614508716155 # Staff
  multiplayer: 0.25

- type: SalaryRoleBonus
  id: MentorshipBonus
  roles:
  - 1294132218918207639 # Mentor
  multiplayer: 0.25

- type: SalaryRoleBonus
  id: Pension
  roles:
  - 1294131297437876254 # Retired
  multiplayer: 0.20

- type: SalaryRoleBonus
  id: SeniorityBonusAlfa
  roles:
  - 1275161200115712071 # AlfaTester
  multiplayer: 0.20

- type: SalaryRoleBonus
  id: SeniorityBonusBeta
  roles:
  - 1294130153651306516 # BetaTester
  multiplayer: 0.10

- type: SalaryRoleBonus
  id: FirstPlacePrize
  roles:
  - 1294132398128107624 # GoldEventWinner
  multiplayer: 0.20

- type: SalaryRoleBonus
  id: SecondPlacePrize
  roles:
  - 1294131865334185994 # SilverEventWinner
  multiplayer: 0.15

- type: SalaryRoleBonus
  id: ThirdPlacePrize
  roles:
  - 1294134860050595862 # CopperEventWinner
  multiplayer: 0.10

- type: SalaryRoleBonus
  id: VeteranPayout
  roles:
  - 1327261545469575179 # Honorary Member
  multiplayer: 0.20

- type: SalaryRoleBonus
  id: SkillAdvancementBonus
  roles:
  - 1308143973684088883 # Changelog
  multiplayer: 0.01 # fun

- type: SalaryRoleBonus
  id: ContributionRoyaltyStarlight
  roles:
  - 1348034282370896012 # Contributor Starlight
  multiplayer: 0.10

- type: SalaryRoleBonus
  id: ContributionRoyaltyWizden
  roles:
  - 929452566092324954 # Contributor Wizden
  multiplayer: 0.10

- type: SalaryRoleBonus
  id: ContributionRoyaltyTrieste
  roles:
  - 1272376299943493716 # Contributor Trieste port
  multiplayer: 0.10
