- type: antag
  id: SubvertedSilicon
  name: roles-antag-subverted-silicon-name
  antagonist: true
  setPreference: false
  objective: roles-antag-subverted-silicon-objective
  # Starlight start
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 24h
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 6h
  playTimeTracker: AntagSubvertedSilicon
  # Starlight end
