using System.Linq;
using System.Numerics;
using Content.Shared._Starlight.Zones;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.Zones.UI;

[GenerateTypedNameReferences]
public sealed partial class ZonePlacerWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entMan = default!;

    private readonly ZonePlacementSystem _placement;
    private readonly List<(Button Button, ProtoId<ZonePrototype> Zone)> _buttons = [];

    public ZonePlacerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _placement = _entMan.System<ZonePlacementSystem>();
    }

    /// <summary>
    /// Populates the zone placer window with a list of zone prototypes.
    /// </summary>
    public void Populate(IEnumerable<ZonePrototype> prototypes)
    {
        ZoneList.RemoveAllChildren();
        _buttons.Clear();

        var zones = prototypes
            .OrderByDescending(zone => zone.Priority)
            .ThenBy(zone => zone.ID);

        foreach (var zone in zones)
        {
            var id = new ProtoId<ZonePrototype>(zone.ID);

            var swatch = new PanelContainer
            {
                MinSize = new Vector2(16, 16),
                PanelOverride = new StyleBoxFlat { BackgroundColor = zone.Color },
                Margin = new Thickness(2, 2, 4, 2),
            };

            var button = new Button
            {
                Text =  Loc.GetString(zone.Name),
                ToggleMode = true,
                HorizontalExpand = true,
                Margin = new Thickness(0, 1),
            };

            button.OnPressed += _ => Select(id);

            _buttons.Add((button, id));

            if (!_buttons.Any(x => x.Zone == _placement.Selected))
                _placement.Selected = null;

            ZoneList.AddChild(new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Children = { swatch, button },
            });
        }

        RefreshPressed();
    }

    private void Select(ProtoId<ZonePrototype> zone)
    {
        _placement.Selected = _placement.Selected == zone ? null : (ProtoId<ZonePrototype>?) zone;
        RefreshPressed();
    }

    private void RefreshPressed()
    {
        foreach (var (button, zone) in _buttons)
            button.Pressed = _placement.Selected == zone;
    }

    protected override void Opened()
    {
        base.Opened();
        _placement.SetActive(true);
    }

    /// <summary>
    /// Closes the zone placer window and deactivates the zone placement system.
    /// </summary>
    public override void Close()
    {
        base.Close();
        _placement.SetActive(false);
    }
}
