using Content.Client.CharacterInfo;
using Content.Client._Starlight.Railroading;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Starlight.Character.Info.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterOverviewControl : Control
{
    private const float RefreshInterval = 1f;

    [Dependency] private IEntityManager _entMan = default!;

    private float _refreshTimer;

    private CardsUIController Cards => UserInterfaceManager.GetUIController<CardsUIController>();

    public CharacterOverviewControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        CardsButton.OnPressed += _ => Cards.OpenCards();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var modulate = Cards.PulseModulate;
        if (CardsButton.Modulate != modulate)
            CardsButton.Modulate = modulate;

        // Objectives are only sent on request, so poll while this tab is on screen.
        _refreshTimer += args.DeltaSeconds;
        if (_refreshTimer < RefreshInterval)
            return;

        _refreshTimer = 0f;
        _entMan.System<CharacterInfoSystem>().RequestCharacterInfo();
    }
}
