using System.Numerics;
using Content.Shared._Starlight.Character.Info.Components;
using Content.Shared.Mind;
using Content.Shared.Roles.Jobs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.Character.Info.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterOOCInfoControl : Control
{
    public CharacterOOCInfoControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetCharacter(EntityUid? target, IEntityManager entityManager, EntityUid? viewer = null)
    {
        if (!target.HasValue)
        {
            ClearCharacter();
            return;
        }

        var mind = entityManager.System<SharedMindSystem>().GetMind(target.Value);

        CharacterView.SetCharacter(target,
            entityManager.System<SharedJobSystem>().MindTryGetJobName(mind, out var jobName)
                ? jobName
                : string.Empty,
            viewer);

        string? oocNotes = null;
        if (entityManager.TryGetComponent(mind, out RoleplayInfoComponent? rpInfoComponent))
        {
            oocNotes = rpInfoComponent.OOCNotes;
        }

        oocNotes = oocNotes != null ? FormattedMessage.RemoveMarkupPermissive(oocNotes) : string.Empty;
        OOCNotes.SetMessage(oocNotes);
        OOCNotes.InvalidateMeasure();
        string? personalNotes = null;
        if (entityManager.TryGetComponent(mind, out MindSecretsComponent? secretsComponent))
        {
            personalNotes = secretsComponent.PersonalNotes;
        }

        HiddenInfoSection.Visible = personalNotes != null;
        personalNotes = personalNotes != null ? FormattedMessage.RemoveMarkupPermissive(personalNotes) : string.Empty;
        PersonalNotes.SetMessage(personalNotes);
        PersonalNotes.InvalidateMeasure();
    }

    public void ClearCharacter()
    {
        CharacterView.ClearCharacter();
        PersonalNotes.Text = null;
        PersonalNotes.InvalidateMeasure();
        OOCNotes.Text = null;
        OOCNotes.InvalidateMeasure();
        HiddenInfoSection.Visible = false;

    }
}