using System.Globalization;
using System.Numerics;
using Content.Shared.Atmos;
using Content.Shared.Atmos.EntitySystems;
using Content.Shared.Atmos.Piping.Trinary.Components;
using Content.Shared.Atmos.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Atmos.UI
{
    /// <summary>
    /// Client-side UI used to control a gas filter.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class GasFilterWindow : DefaultWindow
    {
        private readonly ButtonGroup _buttonGroup = new();

        public HashSet<Gas> SelectedGases = new(); // Starlight
        // public string? CurrentGasId // Starlight

        public event Action<bool>? StatusChanged; // Starlight
        public event Action<string>? FilterTransferRateChanged;
        // public event Action? SelectGasPressed; // Starlight

        #region Starlight
        [Dependency] private IEntityManager _entityManager = default!;
        [Dependency] private IPrototypeManager _prototypeManager = default!;
        private Dictionary<Gas, Button> _gasControls = new();
        private GridContainer _gases => CGasContainer;
        public event Action<HashSet<Gas>>? GasSelectionChanged;
        private Button _selectAll => CSelectAll;
        private Button _deselectAll => CDeselectAll;
        private bool _isUpdatingState;
        #endregion

        public GasFilterWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this); // Starlight add

            ToggleStatusButton.OnToggled += _ => StatusChanged?.Invoke(ToggleStatusButton.Pressed); // Starlight

            FilterTransferRateInput.OnTextChanged += _ => SetFilterRate.Disabled = false;
            SetFilterRate.OnPressed += _ =>
            {
                FilterTransferRateChanged?.Invoke(FilterTransferRateInput.Text);
                SetFilterRate.Disabled = true;
            };

            // Starlight start
            var atmosphereSystem = _entityManager.System<SharedAtmosphereSystem>();
            var allGases = Enum.GetValues<Gas>();
            SetSize = new Vector2(520, 456);


            _selectAll.OnPressed += _ =>
            {
                if (_isUpdatingState) return;

                SelectedGases = new HashSet<Gas>(allGases);
                UpdateGasButtonVisuals();
                GasSelectionChanged?.Invoke(SelectedGases);
            };

            _deselectAll.OnPressed += _ =>
            {
                if (_isUpdatingState) return;

                SelectedGases.Clear();
                UpdateGasButtonVisuals();
                GasSelectionChanged?.Invoke(SelectedGases);
            };

            foreach (var value in allGases)
            {
                ProtoId<GasPrototype> gasProtoId = atmosphereSystem.GetGas(value);
                var gasName = _prototypeManager.Index(gasProtoId).Name;
                var gasButton = new Button
                {
                    Name = value.ToString(),
                    Text = Loc.GetString(gasName),
                    ToggleMode = true,
                    HorizontalExpand = true,
                    HorizontalAlignment = HAlignment.Stretch
                };
                gasButton.OnToggled += args =>
                {
                    if (_isUpdatingState) return;

                    if (args.Pressed)
                        SelectedGases.Add(value);
                    else
                        SelectedGases.Remove(value);

                    GasSelectionChanged?.Invoke(SelectedGases);
                };
                _gasControls.Add(value, gasButton);
                _gases.AddChild(gasButton);
            }
            // Starlight end
        }

        public void SetTransferRate(float rate)
        {
            FilterTransferRateInput.Text = rate.ToString(CultureInfo.CurrentCulture);
        }

        public void SetFilterStatus(bool enabled)
        {
            ToggleStatusButton.Pressed = enabled;
        }

        #region Starlight
        public void UpdateState(GasFilterBoundUserInterfaceState state)
        {
            _isUpdatingState = true;

            SetFilterStatus(state.Enabled);
            SetTransferRate(state.TransferRate);

            SelectedGases = state.FilteredGases != null
                ? new HashSet<Gas>(state.FilteredGases)
                : new HashSet<Gas>();

            UpdateGasButtonVisuals();

            _isUpdatingState = false;
        }

        private void UpdateGasButtonVisuals()
        {
            foreach (var (gas, button) in _gasControls)
            {
                button.Pressed = SelectedGases.Contains(gas);
            }
        }
        #endregion

        /* Starlight BEGIN
        public void SetGasFiltered(string? id, string name)
        {
            CurrentGasId = id;
            CurrentGasLabel.Text = Loc.GetString("comp-gas-filter-ui-filter-gas-current") + $" {name}";
            GasList.ClearSelected();
            SelectGasButton.Disabled = true;
        }

        public void PopulateGasList(IEnumerable<GasPrototype> gases)
        {
            GasList.Add(new ItemList.Item(GasList)
            {
                Metadata = null,
                Text = Loc.GetString("comp-gas-filter-ui-filter-gas-none")
            });

            foreach (var gas in gases)
            {
                var gasName = Loc.GetString(gas.Name);
                GasList.Add(GetGasItem(gas.ID, gasName, GasList));
            }
        }

        private static ItemList.Item GetGasItem(string id, string name, ItemList itemList)
        {
            return new(itemList)
            {
                Metadata = id,
                Text = name
            };
        }

        private void GasListOnItemSelected(ItemList.ItemListSelectedEventArgs obj)
        {
            SelectedGas = (string) obj.ItemList[obj.ItemIndex].Metadata!;
            if(SelectedGas != CurrentGasId) SelectGasButton.Disabled = false;
        }

        private void GasListOnItemDeselected(ItemList.ItemListDeselectedEventArgs obj)
        {
            SelectedGas = CurrentGasId;
            SelectGasButton.Disabled = true;
        }
        Starlight END*/
    }
}
