using System.Linq;
using Content.Shared.Fax;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Fax.UI;

[GenerateTypedNameReferences]
public sealed partial class FaxWindow : DefaultWindow
{
    public event Action? FileButtonPressed;
    public event Action? PaperButtonPressed;
    public event Action? CopyButtonPressed;
    public event Action? SendButtonPressed;
    public event Action? RefreshButtonPressed;
    public event Action<string>? PeerSelected;

    public bool OfficePaper = false;

    public FaxWindow()
    {
        RobustXamlLoader.Load(this);

        PaperButtonPressed += OnPaperButtonPressed;

        FileButton.OnPressed += _ => FileButtonPressed?.Invoke();
        PaperButton.OnPressed += _ => PaperButtonPressed?.Invoke();
        CopyButton.OnPressed += _ => CopyButtonPressed?.Invoke();
        SendButton.OnPressed += _ => SendButtonPressed?.Invoke();
        RefreshButton.OnPressed += _ => RefreshButtonPressed?.Invoke();
        PeerSelector.OnItemSelected += args =>
            PeerSelected?.Invoke(((KnownFax) args.Button.GetItemMetadata(args.Id)!).Address!); // Starlight: string => KnownFax.Address
    }

    public void UpdateState(FaxUiState state)
    {
        CopyButton.Disabled = !state.CanCopy;
        SendButton.Disabled = !state.CanSend;
        FromLabel.Text = state.DeviceName;

        if (state.IsPaperInserted)
        {
            PaperStatusLabel.FontColorOverride = Color.Green;
            PaperStatusLabel.Text = Loc.GetString("fax-machine-ui-paper-inserted");
        }
        else
        {
            PaperStatusLabel.FontColorOverride = Color.Red;
            PaperStatusLabel.Text = Loc.GetString("fax-machine-ui-paper-not-inserted");
        }

        if (state.AvailablePeers.Count == 0)
        {
            PeerSelector.AddItem(Loc.GetString("fax-machine-ui-no-peers"));
            PeerSelector.Disabled = true;
        }

        if (PeerSelector.Disabled && state.AvailablePeers.Count != 0)
        {
            PeerSelector.Clear();
            PeerSelector.Disabled = false;
        }

        // always must be selected destination
        if (string.IsNullOrEmpty(state.DestinationAddress) && state.AvailablePeers.Count != 0)
        {
            PeerSelected?.Invoke(state.AvailablePeers.First().Key);
            return;
        }

        if (state.AvailablePeers.Count != 0)
        {
            PeerSelector.Clear();

            #region Starlight
            /*
             * - Subdivides peers into their assigned Groups;
             * - Groups are ordered by Group.Order, machines without group are sorted to the bottom;
             * - Peers ordered within groups by their individual Order.
             */
            var peers = state.AvailablePeers
                .GroupBy(x => x.Value.GroupOrder)
                .OrderBy(x => x.Key ?? int.MaxValue)
                .SelectMany(group => group
                    .OrderBy(peer => peer.Value.Order));
            #endregion

            foreach (var (address, knownFax) in peers) // Starlight: name => KnownFax, loop ordered peers.
            {
                var id = AddPeerSelect(knownFax); // Starlight: (name, addr) => KnownFax
                if (address == state.DestinationAddress)
                    PeerSelector.Select(id);
            }
        }
    }

    private int AddPeerSelect(KnownFax knownFax) // Starlight: (name, addr) => KnownFax
    {
        #region Starlight
        PeerSelector.AddItem(knownFax.Name);
        PeerSelector.SetItemMetadata(PeerSelector.ItemCount - 1, knownFax);
        PeerSelector.SetItemColor(knownFax.GroupColor ?? Color.DarkGray);
        #endregion
        return PeerSelector.ItemCount - 1;
    }

    private void OnPaperButtonPressed()
    {
        OfficePaper = !OfficePaper;

        if(OfficePaper)
            PaperButton.Text = Loc.GetString("fax-machine-ui-paper-button-office");
        else
            PaperButton.Text = Loc.GetString("fax-machine-ui-paper-button-normal");
    }
}
