using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

#region Starlight
using Robust.Client.UserInterface;
using Content.Client._Starlight.UserInterface;
#endregion

namespace Content.Client.UserInterface.Systems.Chat;

/// <summary>
/// Window which only holds a single chatbox, useful for monitoring multiple chats simultaneously.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ChatWindow : PopOutFancyWindow // Starlight: PopOutFancyWindow
{
    public ChatWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // These are necessary for the controls inside the chatbox to initialize correctly:
        Chatbox.Repopulate();
        var controller = UserInterfaceManager.GetUIController<ChatUIController>();
        controller.UpdateSelectedChannel(Chatbox);
        controller.UpdateLanguageNotifier(Chatbox); // Starlight

        // Starlight BEGIN
        /*
            Turns out that if you open 10 admin chat windows and close them, they basically leak references
            by adding themselves to the ChatUIController._chats list and never getting removed. This fixes that.
        */
        OnFinalClose += () => controller.UnregisterChat(Chatbox);
        // Starlight END
    }

    /// <summary>
    /// Helper method to configure this window to be useful for admins.
    /// Sets incoming filters to only admin chats and output to admin channel
    /// </summary>
    public void ConfigureForAdminChat()
    {
        Chatbox.ChatInput.ChannelSelector.Select(ChatSelectChannel.Admin);
        Chatbox.MainChannel = ChatSelectChannel.Admin; // Starlight

        var filter = Chatbox.ChatInput.FilterButton.Popup;
        foreach (var c in Enum.GetValues(typeof(ChatChannel)))
        {
            var channel = (ChatChannel)c;
            var isAdminInterest = channel == ChatChannel.Admin
                                  || channel == ChatChannel.AdminChat
                                  || channel == ChatChannel.AdminAlert
                                  || channel == ChatChannel.AdminRelated;
            filter.SetActive(channel, isAdminInterest);
        }
    }

    protected override Control Control => Chatbox; // Starlight
}
